<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\List;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\ListItem as ValidateListItem;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:list-item formatting object contains the label and the body of an item in a list.
 *
 * Areas:
 * The fo:list-item formatting object generates one or more normal block-areas. The fo:list-item returns these
 * areas, any page-level-out-of-line areas, and any reference-level-out-of-line areas returned by the children
 * of the fo:list-item.
 *
 * Constraints:
 * No area may have more than one normal child area returned by the same fo:list-item formatting object.
 * The children of each normal area returned by an fo:list-item formatting object must be normal block-areas
 * returned by the fo:list-item-label and the fo:list-item-body flow objects and must be properly ordered.
 * Those returned by the fo:list-item-label must be properly stacked and those returned by the
 * fo:list-item-body must be properly stacked.
 * The children of each normal area returned by an fo:list-item formatting object returned by the
 * fo:list-item-label and fo:list-item-body objects are positioned in the block-progression-direction with
 * respect to each other according to the relative-align trait.
 * In the inline-progression-direction these areas are positioned in the usual manner for properly stacked
 * areas. It is an error if the content-rectangles of the areas overlap.
 * The block-progression-dimension of the content-rectangle of an area generated by the fo:list-item is just
 * large enough so that the allocation-rectangles of all its child areas are contained in it. In particular,
 * the space-before and space-after of the child areas have no effect on the spacing of the list item. For
 * purposes of the block-stacking constraints the areas generated by fo:list-item are treated as if there they
 * have a fence preceding and a fence following them.
 *
 * Note:
 * These areas are not reference-areas, hence the indents on all objects within them are measured relative to
 * the reference-area that holds the content of the fo:list-block.
 *
 * Contents:
 * (list-item-label,list-item-body)
 *
 * In addition this formatting object may have a sequence of zero or more fo:markers as its initial children.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_list-item
 */
class ListItem extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateListItem;
}
