<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\AbsolutePositionType;

/**
 * A Property Derived from a CSS2 Property.
 *
 * XSL Definition:
 * - Value:  auto | absolute | fixed | inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  N/A
 * - Media:  visual
 *
 * The following additional restrictions apply for paged presentations:
 * - Only objects with absolute-position="auto" may have page/column breaks. For other values any keep and
 *   break properties are ignored.
 * - The area generated is a descendant of the page-area where the first area from the object would have
 *   been placed had the object had absolute-position="auto" specified.
 *
 * If the value is "absolute" or "fixed", any normal areas generated by the formatting object have their
 * area-class changed to xsl-absolute or xsl-fixed, respectively.
 *
 * @link https://www.w3.org/TR/xsl11/#absolute-position
 */
class AbsolutePosition extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('absolute-position', AbsolutePositionType::class);
    }

    public function getDefaultValue(): string
    {
        return AbsolutePositionType::AUTO;
    }
}
