<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\AlignmentAdjustType;

/**
 * XSL Definition:
 * - Value:  auto | baseline | before-edge | text-before-edge | middle | central | after-edge |
 *     text-after-edge | ideographic | alphabetic | hanging | mathematical | `<percentage>` | `<length>` |
 *     inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  see prose
 * - Media:  visual
 *
 * The "alignment-adjust" property allows more precise alignment of areas generated by formatting
 * objects, in particular for formatting objects, such as graphics, that do not have a baseline-table
 * or lack the desired baseline in their baseline-table. With the "alignment-adjust" property, the
 * position of the baseline identified by the "alignment-baseline" can be explicitly determined.
 *
 * Implementations must support at least one of the "alignment-adjust" values defined in this Recommendation.
 *
 * @link https://www.w3.org/TR/xsl11/#alignment-adjust
 */
class AlignmentAdjust extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('alignment-adjust', AlignmentAdjustType::class);
    }

    public function getDefaultValue(): string
    {
        return AlignmentAdjustType::AUTO;
    }
}
