<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\CompoundTypedAttribute;
use Lsa\Xsl\Core\Validation\Types\BlockProgressionDimensionMaximumType;
use Lsa\Xsl\Core\Validation\Types\BlockProgressionDimensionOptimumType;
use Lsa\Xsl\Core\Validation\Types\BlockProgressionDimensionType;
use Lsa\Xsl\Core\Validation\Types\Xsl\LengthType;

/**
 * Writing-mode Relative Equivalent of a CSS2 Property.
 * - Value:  auto | `<length>` | `<percentage>` | `<length-range>` | inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  see prose
 * - Media:  visual
 *
 * This property specifies the block-progression-dimension of the content-rectangle for each area generated
 * by this formatting object. The user may specify an explicit size (`<length>` or `<percentage>`) or a
 * `<length-range>`, allowing the size to be adjusted by the formatter.
 * This property does not apply when the "line-height" property applies to the same dimension of the areas
 * generated by this formatting object.
 *
 * @link https://www.w3.org/TR/xsl11/#block-progression-dimension
 */
class BlockProgressionDimension extends CompoundTypedAttribute
{
    public function __construct()
    {
        parent::__construct(
            'block-progression-dimension',
            BlockProgressionDimensionType::class,
            [
                'minimum' => LengthType::class,
                'optimum' => BlockProgressionDimensionOptimumType::class,
                'maximum' => BlockProgressionDimensionMaximumType::class,
            ]
        );
    }
}
