<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\BreaksType;

/**
 * XSL Definition:
 * - Value:  auto | column | page | even-page | odd-page | inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  N/A
 * - Media:  visual
 *
 * Specifies that the first area generated by formatting this formatting object shall be the first one
 * placed in a particular context (e.g., page-area, column-area).
 *
 * This property has no effect when it appears on an fo:table-row formatting object in which there is any
 * row spanning occurring that includes both the current fo:table-row and the previous one.
 */
class BreakBefore extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('break-before', BreaksType::class);
    }

    public function getDefaultValue(): string
    {
        return BreaksType::AUTO;
    }
}
