<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\ClearType;

/**
 * CSS2 Definition:
 * - Value:  start | end | left | right | inside | outside | both | none | inherit
 * - Initial:  none
 * - Inherited:  no
 * - Percentages:  N/A
 * - Media:  visual
 *
 * This property indicates which sides of an element's box(es) may not be adjacent to an earlier
 * floating box. (It may be that the element itself has floating descendants; the 'clear' property
 * has no effect on those.)
 *
 * This property may only be specified for block-level elements (including floats). For compact
 * and run-in boxes, this property applies to the final block box to which the compact or run-in
 * box belongs.
 *
 * XSL modifications to the CSS definition:
 * - A start-float is defined to mean an area with area-class "xsl-side-float" that was generated
 *   by an fo:float with property "float" specified as "left" or "start".
 * - An end-float is defined to mean an area with area-class "xsl-side-float" that was generated
 *   by an fo:float with property "float" specified as "right" or "end".
 * - An inside-float is defined to mean an area with area-class "xsl-side-float" that was generated
 *   by an fo:float with property "float" specified as "inside".
 * - An outside-float is defined to mean an area with area-class "xsl-side-float" that was generated
 *   by an fo:float with property "float" specified as "outside".
 * - A side-float is defined to mean either a start-float or an end-float.
 * - An area is defined to "clear" a side-float if the before-edge of the area's border-rectangle is
 *   positioned to be after the after-edge of the float, or if the area is not a descendant of the
 *   side-float's parent reference-area.
 * - A block-level formatting object is defined "to clear" a side-float if the areas generated by
 *   the formatting object clear the side-float.
 * - In XSL this property applies to block-level formatting objects and fo:float.
 * - The clear property when applied to an fo:float that generates side-floats does not apply to the
 *   fo:float's anchor-area.
 * - When a block-level formatting object is constrained by the "clear" property, its space-before
 *   property component values may be altered as necessary for each area that it generates, in order
 *   to meet the constraint. The alterations are constrained to produce the minimum additional space
 *   required to meet the constraint of the "clear" property.
 *
 * Note: Depending on how near a side-float's after-edge is to the after-edge of its parent
 * reference-area, a block-level formatting object may not be able to generate an area that is a
 * descendant of the side-float's parent reference-area. In this case the first block-area generated
 * by the formatting object must be placed in one of the following reference-areas in the
 * reference-area chain that contains the side-float's parent reference-area.
 *
 * @link https://www.w3.org/TR/xsl11/#clear
 * @link http://www.w3.org/TR/REC-CSS2/visuren.html#propdef-clear
 */
class Clear extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('clear', ClearType::class);
    }

    public function getDefaultValue(): string
    {
        return ClearType::NONE;
    }
}
