<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\FloatType;

/**
 * CSS2 Definition:
 * - Value:  before | start | end | left | right | inside | outside | none | inherit
 * - Initial:  none
 * - Inherited:  no
 * - Percentages:  N/A
 * - Media:  visual
 *
 * This property specifies whether a box should float to the left, right, or not at all. It may be
 * set for elements that generate boxes that are not absolutely positioned.
 *
 * Here are the precise rules that govern the behavior of floats:
 * 1. The left outer edge of a left-floating box may not be to the left of the left edge of its
 * containing block. An analogous rule holds for right-floating elements.
 * 2. If the current box is left-floating, and there are any left floating boxes generated by
 * elements earlier in the source document, then for each such earlier box, either the left outer
 * edge of the current box must be to the right of the right outer edge of the earlier box, or its
 * top must be lower than the bottom of the earlier box. Analogous rules hold for right-floating
 * boxes.
 * 3. The right outer edge of a left-floating box may not be to the right of the left outer edge
 * of any right-floating box that is to the right of it. Analogous rules hold for right-floating
 * elements.
 * 4. A floating box's outer top may not be higher than the top of its containing block.
 * 5. The outer top of a floating box may not be higher than the outer top of any block or floated
 * box generated by an element earlier in the source document.
 * 6. The outer top of an element's floating box may not be higher than the top of any line-box
 * containing a box generated by an element earlier in the source document.
 * 7. A left-floating box that has another left-floating box to its left may not have its right
 * outer edge to the right of its containing block's right edge. (Loosely: a left float may not
 * stick out at the right edge, unless it is already as far to the left as possible.) An analogous
 * rule holds for right-floating elements.
 * 8. A floating box must be placed as high as possible.
 * 9. A left-floating box must be put as far to the left as possible, a right-floating box as far
 * to the right as possible. A higher position is preferred over one that is further to the
 * left/right.
 *
 * XSL modifications to the CSS definition:
 * - The following values have been added for XSL: "before", "start", "end", "inside", and "outside".
 * - In XSL this property applies only to fo:float
 *
 * This property determines the area-class trait of the block-areas returned by the fo:float, which
 * controls the placement and parent of these block-areas.
 *
 * @link https://www.w3.org/TR/xsl11/#float
 */
class FloatProperty extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('float', FloatType::class);
    }

    public function getDefaultValue(): string
    {
        return FloatType::NONE;
    }
}
