<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\HeightType;

/**
 * CSS2 Definition:
 * - Value:  `<length>` | `<percentage>` | auto | inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  see prose
 * - Media:  visual
 *
 * This property specifies the content height of boxes generated by block-level and replaced elements.
 *
 * This property does not apply to non-replaced inline-level elements. The height of a non-replaced
 * inline element's boxes is given by the element's (possibly inherited) 'line-height' value.
 *
 * Negative values for 'height' are illegal.
 *
 * @link https://www.w3.org/TR/xsl11/#height
 * @link http://www.w3.org/TR/REC-CSS2/visudet.html#propdef-height
 */
class Height extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('height', HeightType::class);
    }

    public function getDefaultValue(): string
    {
        return HeightType::AUTO;
    }
}
