<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\CompoundTypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\InlineProgressionDimensionMaximumType;
use Lsa\Xsl\Core\Validation\Types\InlineProgressionDimensionOptimumType;
use Lsa\Xsl\Core\Validation\Types\InlineProgressionDimensionType;
use Lsa\Xsl\Core\Validation\Types\Xsl\LengthType;

/**
 * Writing-mode Relative Equivalent of a CSS2 Property.
 * - Value:  auto | `<length>` | `<percentage>` | `<length-range>` | inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  see prose
 * - Media:  visual
 *
 * This property specifies the inline-progression-dimension of the content-rectangle for each
 * area generated by this formatting object. The user may specify an explicit size (`<length>`
 * or `<percentage>`) or a `<length-range>`, allowing the size to be adjusted by the formatter.
 *
 * This property does not apply when the "line-height" property applies to the same dimension
 * of the areas generated by this formatting object.
 *
 * Values have the following meanings:
 *
 * `<length>`:
 * Specifies a fixed inline-progression-dimension.
 * Specifying inline-progression-dimension=`<length>` will set:
 * - `inline-progression-dimension.minimum=<length>`
 * - `inline-progression-dimension.optimum=<length>`
 * - `inline-progression-dimension.maximum=<length>`
 *
 * `<percentage>`:
 * Specifies a percentage inline-progression-dimension. The percentage is calculated with respect to the
 * corresponding dimension of the closest area ancestor that was generated by a block-level formatting
 * object. If that dimension is not specified explicitly (i.e., it depends on content's
 * inline-progression-dimension), the value is interpreted as "auto".
 * Specifying `inline-progression-dimension=<percentage>` will set:
 * - `inline-progression-dimension.minimum=<percentage>`
 * - `inline-progression-dimension.optimum=<percentage>`
 * - `inline-progression-dimension.maximum=<percentage>`
 *
 * `<length-range>`
 * Specifies the dimension as a length-range, consisting of:
 * - inline-progression-dimension.optimum:
 *     This is the preferred dimension of the area created, if minimum and maximum are identical, the
 *     area is of a fixed dimension. If they are, respectively, smaller and larger than optimum, then
 *     the area may be adjusted in dimension within that range.
 *     A value of "auto" may be specified for optimum, indicating that there is no preferred dimension,
 *     but that the intrinsic or resolved dimension of the area should be used. If minimum and/or
 *     maximum are not also auto, then the dimension shall be constrained between those limits.
 * - inline-progression-dimension.minimum
 * - inline-progression-dimension.maximum
 *     A value of "auto" may be specified for inline-progression-dimension.maximum. This indicates that
 *     there is no absolute maximum limit, and the object may be sized to its intrinsic size.
 *
 * Negative values for inline-progression-dimension.minimum, inline-progression-dimension.optimum, and
 * inline-progression-dimension.maximum are invalid and are treated as if "0pt" had been specified.
 *
 * @link https://www.w3.org/TR/xsl11/#inline-progression-dimension
 */
class InlineProgressionDimension extends CompoundTypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct(
            'inline-progression-dimension',
            InlineProgressionDimensionType::class,
            [
                'minimum' => LengthType::class,
                'optimum' => InlineProgressionDimensionOptimumType::class,
                'maximum' => InlineProgressionDimensionMaximumType::class,
            ]
        );
    }

    public function getDefaultValue(): string
    {
        return InlineProgressionDimensionType::AUTO;
    }
}
