<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Traits\InheritableAttribute;
use Lsa\Xsl\Core\Validation\Types\LastLineEndIndentType;

/**
 * XSL Definition:
 * - Value:  <length> | <percentage> | inherit
 * - Initial:  0pt
 * - Inherited:  yes
 * - Percentages:  refer to inline-progression-dimension of closest ancestor block-area that is not a line-area
 * - Media:  visual
 *
 * Specifies an indent to be applied to the last line-area child of the last block-area generated and
 * returned by the formatting object, and to any line-area generated by the formatting object whose
 * following sibling is a block-area that is not a line-area. It is added to the block's end-edge.
 * Positive values indent the edge, negative values outdent the edge.
 */
class LastLineEndIndent extends TypedAttribute implements HasDefaultValue
{
    use InheritableAttribute;

    public function __construct()
    {
        parent::__construct('last-line-end-indent', LastLineEndIndentType::class);
    }

    public function getDefaultValue(): string
    {
        return '0pt';
    }
}
