<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Traits\InheritableAttribute;
use Lsa\Xsl\Core\Validation\Types\LineHeightType;

/**
 * CSS2 Definition:
 * - Value:  normal | `<length>` | `<number>` | `<percentage>` | `<space>` | inherit
 * - Initial:  normal
 * - Inherited:  yes
 * - Percentages:  refer to the font size of the element itself
 * - Media:  visual
 *
 * If the property is set on a block-level element whose content is composed of inline-level elements,
 * it specifies the minimal height of each generated inline box.
 *
 * If the property is set on an inline-level element, it specifies the exact height of each box
 * generated by the element. (Except for inline replaced elements, where the height of the box is given
 * by the "height" property.)
 *
 * When an element contains text that is rendered in more than one font, user agents should determine
 * the "line-height" value according to the largest font size.
 *
 * Generally, when there is only one value of "line-height" for all inline boxes in a paragraph (and no
 * tall images), the above will ensure that baselines of successive lines are exactly "line-height"
 * apart. This is important when columns of text in different fonts have to be aligned, for example in
 * a table.
 *
 * Note that replaced elements have a "font-size" and a "line-height" property, even if they are not
 * used directly to determine the height of the box. The "font-size" is, however, used to define the
 * "em" and "ex" units, and the "line-height" has a role in the "vertical-align" property.
 *
 * XSL modifications to the CSS definition:
 *
 * In XSL the "line-height" property is used in determining the half-leading trait.
 *
 * XSL adds the following value with the following meaning: `<space>`
 * - Specifies the minimum, optimum, and maximum values, the conditionality, and precedence of the
 * "line-height" that is used in determining the half-leading.
 * - Negative values for line-height.minimum, line-height.optimum, and line-height.maximum are invalid
 * and will be interpreted as 0pt.
 * - The line-height.conditionality setting can be used to control the half-leading above the first
 * line or after the last line that is placed in a reference-area.
 * - The line-height.precedence setting can be used to control the merging of the half-leading with
 * other spaces.
 *
 * If line-height is specified using `<length>`, `<percentage>`, or `<number>`, the formatter shall convert
 * the single value to a space-specifier with the subfields interpreted as follows:
 * - line-height.minimum: the resultant computed value (as a length) of the `<length>`, `<percentage>`,
 * or `<number>`.
 * - line-height.optimum: the resultant computed value (as a length) of the `<length>`, `<percentage>`,
 * or `<number>`.
 * - line-height.maximum: the resultant computed value (as a length) of the `<length>`, `<percentage>`,
 * or `<number>`.
 * - line-height.precedence: force.
 * - line-height.conditionality: retain
 *
 * @link https://www.w3.org/TR/xsl11/#line-height
 */
class LineHeight extends TypedAttribute implements HasDefaultValue
{
    use InheritableAttribute;

    public function __construct()
    {
        parent::__construct('line-height', LineHeightType::class);
    }

    public function getDefaultValue(): string
    {
        return LineHeightType::NORMAL;
    }
}
