<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\RoleType;

/**
 * XSL Definition:
 * - Value:  `<string>` | `<uri-specification>` | none | inherit
 * - Initial:  none
 * - Inherited:  no
 * - Percentages:  N/A
 * - Media:  all
 *
 * This property provides a hint for alternate renderers (aural readers, etc.) as to the role of the
 * XML element or elements that were used to construct this formatting object, if one could be
 * identified during XSLT tree construction. This information can be used to prepare alternate
 * renderings when the normal rendering of a formatting object is not appropriate or satisfactory;
 * for example, the role information can be used to provide better aural renderings of visually
 * formatted material.
 *
 * To aid alternate renderers, the <string> value should be the qualified name (QName [XML Names] or
 * [XML Names 1.1]) of the element from which this formatting object is constructed. If a QName does
 * not provide sufficient context, the <uri-specification> can be used to identify an RDF resource
 * that describes the role in more detail. This RDF resource may be embedded in the result tree and
 * referenced with a relative URI or fragment identifier, or the RDF resource may be external to the
 * result tree. This specification does not define any standard QName or RDF vocabularies; these are
 * frequently application area dependent. Other groups, for example the Dublin Core, have defined such
 * vocabularies.
 *
 * This property is not inherited, but all subsidiary nodes of this formatting object that do not bear
 * a role property should utilize the same alternate presentation properties. (It is not inherited
 * because knowledge of the start and end of the formatting object subtree generated by the element
 * may be needed by the renderer.)
 *
 * @link https://www.w3.org/TR/xsl11/#role
 */
class Role extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('role', RoleType::class);
    }

    public function getDefaultValue(): string
    {
        return RoleType::NONE;
    }
}
