<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\CompoundTypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\SpaceAfterType;
use Lsa\Xsl\Core\Validation\Types\Xsl\ConditionalityType;
use Lsa\Xsl\Core\Validation\Types\Xsl\LengthType;
use Lsa\Xsl\Core\Validation\Types\Xsl\SpacePrecedenceType;

/**
 * XSL Definition:
 * - Value:  `<space>` | inherit
 * - Initial:  space.minimum=0pt, .optimum=0pt, .maximum=0pt, .conditionality=discard, .precedence=0
 * - Inherited:  no
 * - Percentages:  N/A (Differs from margin-bottom in CSS)
 * - Media:  visual
 *
 * Specifies the value of the space-specifier for the space after the areas generated by this formatting
 * object. A definition of space-specifiers, and the interaction between space-specifiers occurring in
 * sequence are given in 4.3 Spaces and Conditionality.
 *
 * Note:
 * A common example of such a sequence is the "space-after" on one area and the "space-before" of its next
 * sibling.
 *
 * @link https://www.w3.org/TR/xsl11/#space-after
 * @link https://www.w3.org/TR/xsl11/#spacecond
 */
class SpaceAfter extends CompoundTypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct(
            'space-after',
            SpaceAfterType::class,
            [
                'minimum' => LengthType::class,
                'optimum' => LengthType::class,
                'maximum' => LengthType::class,
                'conditionality' => ConditionalityType::class,
                'precedence' => SpacePrecedenceType::class,
            ]
        );
    }

    public function getDefaultValue(): string
    {
        return '0pt';
    }
}
