<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\CompoundTypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\SpaceStartType;
use Lsa\Xsl\Core\Validation\Types\Xsl\ConditionalityType;
use Lsa\Xsl\Core\Validation\Types\Xsl\LengthType;
use Lsa\Xsl\Core\Validation\Types\Xsl\SpacePrecedenceType;

/**
 * XSL Definition:
 * - Value:  `<space>` | `<percentage>` | inherit
 * Initial:  space.minimum=0pt, .optimum=0pt, .maximum=0pt, .conditionality=discard, .precedence=0
 * Inherited:  no
 * Percentages:  refer to inline-progression-dimension of closest ancestor block-area that is not a line-area
 * Media:  visual
 *
 * Specifies the minimum, optimum, and maximum values for the space before any areas generated by this
 * formatting object and the conditionality and precedence of this space.
 * Specifies the value of the space-specifier for the space before the areas generated by this formatting
 * object. A definition of space-specifiers, and the interaction between space-specifiers occurring in
 * sequence are given in 4.3 Spaces and Conditionality.
 *
 * Note:
 * A common example of such a sequence is the "space-end" on one area and the "space-start" of its next sibling.
 *
 * @link https://www.w3.org/TR/xsl11/#space-start
 */
class SpaceStart extends CompoundTypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct(
            'space-start',
            SpaceStartType::class,
            /**
             * Erroneous type inference from PHPStan
             *
             * @var array<string,class-string<Type>>
             */
            [
                'minimum' => LengthType::class,
                'optimum' => LengthType::class,
                'maximum' => LengthType::class,
                'conditionality' => ConditionalityType::class,
                'precedence' => SpacePrecedenceType::class,
            ]
        );
    }

    public function getDefaultValue(): string
    {
        return '0pt';
    }
}
