<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\SpanType;

/**
 * XSL Definition:
 * - Value:  none | all | inherit
 * - Initial:  none
 * - Inherited:  no
 * - Percentages:  N/A
 * - Media:  visual
 *
 * Specifies if a block-level object should be placed in the current column or should span all
 * columns of a multi-column region.
 *
 * Note: This only has effect on areas returned by a flow; e.g. block-areas generated by fo:block
 * children of an fo:flow. Children and further descendants of these areas take on the spanning
 * characteristic of their parent.
 *
 * @link https://www.w3.org/TR/xsl11/#span
 */
class Span extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('span', SpanType::class);
    }

    public function getDefaultValue(): string
    {
        return SpanType::NONE;
    }
}
