<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Traits\InheritableAttribute;
use Lsa\Xsl\Core\Validation\Types\StartIndentType;

/**
 * XSL Definition:
 * - Value:  `<length>` | `<percentage>` | inherit
 * - Initial:  0pt
 * - Inherited:  yes
 * - Percentages:  refer to inline-progression-dimension of containing reference-area
 * - Media:  visual
 *
 * For each block-area generated by this formatting object, specifies the distance from the start-edge of
 * the content-rectangle of the containing reference-area to the start-edge of the content-rectangle of that
 * block-area.
 *
 * This property may have a negative value, which indicates an outdent.
 *
 * @link https://www.w3.org/TR/xsl11/#start-indent
 */
class StartIndent extends TypedAttribute implements HasDefaultValue
{
    use InheritableAttribute;

    public function __construct()
    {
        parent::__construct('start-indent', StartIndentType::class);
    }

    public function getDefaultValue(): string
    {
        return '0pt';
    }
}
