<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Traits\InheritableAttribute;
use Lsa\Xsl\Core\Validation\Types\TextAlignLastType;

/**
 * XSL Definition:
 * - Value:  relative | start | center | end | justify | inside | outside | left | right | inherit
 * - Initial:  relative
 * - Inherited:  yes
 * - Percentages:  N/A
 * - Media:  visual
 *
 * Specifies the alignment of the last line-area child of the last block-area generated and
 * returned by the formatting object, and to any line-area generated by the formatting object
 * whose following sibling is a block-area that is not a line-area, and any lines in the block
 * ending in U+000A.
 *
 * @link https://www.w3.org/TR/xsl11/#text-align-last
 */
class TextAlignLast extends TypedAttribute implements HasDefaultValue
{
    use InheritableAttribute;

    public function __construct()
    {
        parent::__construct('text-align-last', TextAlignLastType::class);
    }

    public function getDefaultValue(): string
    {
        return TextAlignLastType::RELATIVE;
    }
}
