<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\TextDecorationType;

/**
 * CSS2 Definition:
 * - Value:  none | [ [ underline | no-underline] || [ overline | no-overline ] ||
 *     [ line-through | no-line-through ] || [ blink | no-blink ] ] | inherit
 * - Initial:  none
 * - Inherited:  no, but see prose
 * - Percentages:  N/A
 * - Media:  visual
 *
 * Specifies the "height" to be used for the ascent above the dominant baseline.
 *
 * This property describes decorations that are added to the text of an element. If the property is
 * specified for a block-level element, it affects all inline-level descendants of the element. If
 * it is specified for (or affects) an inline-level element, it affects all boxes generated by the
 * element. If the element has no content or no text content (e.g., the IMG element in HTML), user
 * agents must ignore this property.
 *
 * XSL modifications to the CSS definition:
 * - In XSL, the specification of the "underline" value is expanded as follows: The placement of the
 * underline depends on whether the "inline-progression-direction" is oriented horizontally or
 * vertically and on the "language" property. For horizontal text the underline is placed below the
 * text. For vertical text the placement depends on the value of the "language" property: the
 * underline is placed on or close to either the before-edge or the after-edge of the underlined text.
 *
 * Note: This specification does not specify the dependence of the placement of the vertical underline
 * on the "language". It is possible for two conforming XSL processors to place the underline on
 * different sides of the vertical text. For Japanese, the placement of the underline is typically
 * close to the before-edge of the underlined text. For other languages, such as Chinese, the typical
 * placement is close to the after-edge of the underlined text. Implementers should not make any
 * assumptions about how underlines are placed in particular languages and should properly research
 * the languages that they wish to support.
 *
 * Note: Some fonts have an attribute that suggests where to place the underline for text in that font.
 * That value is likely to apply only when the "inline-progression-direction" is oriented horizontally.
 *
 * - XSL adds the following values: no-underline, no-overline, no-line-through, no-blink
 *
 * @link https://www.w3.org/TR/xsl11/#text-decoration
 * @link http://www.w3.org/TR/REC-CSS2/text.html#propdef-text-decoration
 */
class TextDecoration extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('text-decoration', TextDecorationType::class);
    }

    public function getDefaultValue(): string
    {
        return TextDecorationType::NONE;
    }
}
