<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\ShorthandTypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\VerticalAlignType;

/**
 * CSS2 Definition:
 * - Value: baseline | middle | sub | super | text-top | text-bottom | <percentage> | <length> | top | bottom
 *  | inherit
 * - Initial: baseline
 * - Inherited: no
 * - Percentages: refer to the 'line-height' of the element itself
 * - Media: visual
 *
 * This property affects the vertical positioning inside a line box of the boxes generated by an inline-level
 * element. The following values only have meaning with respect to a parent inline-level element, or to a parent
 * block-level element, if that element generates anonymous inline boxes; they have no effect if no such parent
 * exists.
 * Note: Values of this property have slightly different meanings in the context of tables. Please consult the
 * section on table height algorithms for details.
 *
 * Values have the following meanings:
 *
 * `baseline`:
 * - Align the baseline of the box with the baseline of the parent box. If the box doesn't have a baseline,
 *   align the bottom of the box with the parent's baseline.
 *
 * `middle`:
 * - Align the vertical midpoint of the box with the baseline of the parent box plus half the x-height of the
 *   parent.
 *
 * `sub`:
 * - Lower the baseline of the box to the proper position for subscripts of the parent's box. (This value has
 *   no effect on the font size of the element's text.)
 *
 * `super`:
 * - Raise the baseline of the box to the proper position for superscripts of the parent's box. (This value
 *   has no effect on the font size of the element's text.)
 *
 * `text-top`:
 * - Align the top of the box with the top of the parent element's font.
 *
 * `text-bottom`:
 * - Align the bottom of the box with the bottom of the parent element's font.
 *
 * `top`:
 * - Align the top of the box with the top of the line box.
 *
 * `bottom`:
 * - Align the bottom of the box with the bottom of the line box.
 *
 * `<percentage>`:
 * - Raise (positive value) or lower (negative value) the box by this distance (a percentage of the
 *   "line-height" value). The value "0%" means the same as "baseline".
 *
 * `<length>`:
 * - Raise (positive value) or lower (negative value) the box by this distance. The value "0cm" means the same
 *   as "baseline".
 *
 * Note: Values of this property have slightly different meanings in the context of tables. Please consult the
 * section on table height algorithms for details.
 *
 * XSL modifications to the CSS definition:
 * The CSS property shall be treated as a shorthand by XSL and maps as follows:
 *
 * `baseline`:
 * - alignment-baseline="baseline"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `top`:
 * - alignment-baseline="before-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `text-top`:
 * - alignment-baseline="text-before-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `middle`:
 * - alignment-baseline="middle"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `bottom`:
 * - alignment-baseline="after-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `text-bottom`:
 * - alignment-baseline="text-after-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `sub`:
 * - alignment-baseline="baseline"
 * - alignment-adjust="auto"
 * - baseline-shift="sub"
 * - dominant-baseline="auto"
 *
 * `super`:
 * - alignment-baseline="baseline"
 * - alignment-adjust="auto"
 * - baseline-shift="super"
 * - dominant-baseline="auto"
 *
 * `<percentage>`:
 * - alignment-baseline="baseline"
 * - alignment-adjust="`<percentage>`"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `<length>`:
 * - alignment-baseline="baseline"
 * - alignment-adjust="`<length>`"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * @link https://www.w3.org/TR/xsl11/#vertical-align
 * @link http://www.w3.org/TR/REC-CSS2/visudet.html#propdef-vertical-align
 */
class VerticalAlign extends ShorthandTypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct(
            'vertical-align',
            VerticalAlignType::class,
            [
                AlignmentAdjust::class,
                AlignmentBaseline::class,
                BaselineShift::class,
                DominantBaseline::class,
            ]
        );
    }

    public function getDefaultValue(): string
    {
        return VerticalAlignType::BASELINE;
    }
}
