<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Traits\InheritableAttribute;
use Lsa\Xsl\Core\Validation\Types\VisibilityType;

/**
 * CSS2 Definition:
 * - Value:  visible | hidden | collapse | inherit
 * - Initial:  visible
 * - Inherited:  yes
 * - Percentages:  N/A
 * - Media:  visual
 *
 * The 'visibility' property specifies whether the boxes generated by an element are rendered.
 * Invisible boxes still affect layout (set the 'display' property to 'none' to suppress box
 * generation altogether).
 *
 * This property may be used in conjunction with scripts to create dynamic effects.
 *
 * XSL modifications to the CSS definition:
 * - Changed initial value to visible; (it is "inherit" in CSS) and made it an inherited property.
 *
 * @link https://www.w3.org/TR/xsl11/#visibility
 */
class Visibility extends TypedAttribute implements HasDefaultValue
{
    use InheritableAttribute;

    public function __construct()
    {
        parent::__construct('visibility', VisibilityType::class);
    }

    public function getDefaultValue(): string
    {
        return VisibilityType::VISIBLE;
    }
}
