<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Traits\InheritableAttribute;
use Lsa\Xsl\Core\Validation\Types\WidowsType;

/**
 * CSS2 Definition:
 * - Value:  <integer> | inherit
 * - Initial:  2
 * - Inherited:  yes
 * - Percentages:  N/A
 * - Media:  visual
 *
 * The "orphans" property specifies the minimum number of lines of a paragraph that must be left at the
 * bottom of a page. The "widows" property specifies the minimum number of lines of a paragraph that must be
 * left at the top of a page.
 *
 * XSL modifications to the CSS definition:
 * - In XSL the "orphans" property specifies the minimum number of line-areas in the first area generated by
 *   the formatting object. The "widows" property specifies the minimum number of line-areas in the last area
 *   generated by the formatting object.
 *
 * @link https://www.w3.org/TR/xsl11/#widows
 * @link http://www.w3.org/TR/REC-CSS2/page.html#propdef-widows
 */
class Widows extends TypedAttribute implements HasDefaultValue
{
    use InheritableAttribute;

    public function __construct()
    {
        parent::__construct('widows', WidowsType::class);
    }

    public function getDefaultValue(): string
    {
        return '2';
    }
}
