<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Properties;

use Lsa\Xml\Utils\Validation\TypedAttribute;
use Lsa\Xsl\Core\Contracts\HasDefaultValue;
use Lsa\Xsl\Core\Validation\Types\WidthType;

/**
 * CSS2 Definition:
 * - Value:  `<length>` | `<percentage>` | auto | inherit
 * - Initial:  auto
 * - Inherited:  no
 * - Percentages:  refer to width of containing block
 * - Media:  visual
 *
 * This property specifies the content width of boxes generated by block-level and replaced
 * elements.
 *
 * This property does not apply to non-replaced inline-level elements. The width of a non-replaced
 * inline element's boxes is that of the rendered content within them (before any relative offset
 * of children). Recall that inline boxes flow into line boxes. The width of line boxes is given
 * by their containing block, but may be shorted by the presence of floats.
 *
 * The width of a replaced element's box is intrinsic and may be scaled by the user agent if the
 * value of this property is different than 'auto'.
 *
 * XSL modifications to the CSS definition:
 * In XSL, this property is mapped to either "inline-progression-dimension" or
 * "block-progression-dimension", based on the applicable values of the "writing-mode" and
 * "reference-orientation" properties. Details on the mapping are given in
 * 5 Property Refinement / Resolution.
 *
 * @link https://www.w3.org/TR/xsl11/#width
 * @link http://www.w3.org/TR/REC-CSS2/page.html#propdef-width
 * @link https://www.w3.org/TR/xsl11/#refinement
 */
class Width extends TypedAttribute implements HasDefaultValue
{
    public function __construct()
    {
        parent::__construct('width', WidthType::class);
    }

    public function getDefaultValue(): string
    {
        return WidthType::AUTO;
    }
}
