<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\OutOfLine;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Block\Block;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\FloatElement as ValidateFloatElement;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:float formatting object is typically used either to cause an image to be positioned in a separate
 * area at the beginning of a page, or to cause an image to be positioned to one side, with normal content
 * flowing around and along-side the image.
 *
 * Areas:
 * The fo:float generates an optional single area with area-class "xsl-anchor", and one or more block-areas
 * that all share the same area-class, which is either "xsl-before-float", "xsl-side-float" or "xsl-normal"
 * as specified by the "float" property. (An fo:float generates normal block-areas if its "float" property
 * value is "none".)
 * Areas with area-class "xsl-side-float" are reference areas.
 * An area with area-class "xsl-before-float" is placed as a child of a before-float-reference-area.
 * The optional area with area-class "xsl-anchor" is not generated if the "float" property value is "none",
 * or if, due to an error as described in the constraints section, the fo:float shall be formatted as though
 * its "float" property was "none". Otherwise, the area with area-class "xsl-anchor" shall be generated.
 * The area with area-class "xsl-anchor" has no children, and is an inline-area, except where this would
 * violate the constraints that (a.) any area's children must be either block-areas or inline-areas, but not
 * a mixture, and (b.) the children of a line-area may not consist only of anchor areas. In the case where
 * an inline-area would violate these constraints, the fo:float must instead generate a block-area.
 *
 * Constraints:
 * The normal inline-area generated by the fo:float shall be placed in the area tree as though the fo:float
 * had a "keep-with-previous" property with value "always". The inline-area has a length of zero for both the
 * inline-progression-dimension and block-progression-dimension.
 * The term anchor-area is used here to mean the area with area-class "xsl-anchor" generated by the fo:float.
 * An area with area-class "xsl-side-float" is a side-float.
 * No area may have more than one child block-area with the same area-class returned by the same fo:float
 * formatting object.
 * Areas with area-class "xsl-before-float" must be properly ordered within the area tree relative to other
 * areas with the same area-class.
 * The padding-, border-, and content-rectangles of the block-areas generated by fo:float all coincide. That
 * is, the padding and border are zero at all edges of the area.
 *
 * The following constraints apply to fo:float formatting objects that generate areas with area-class
 * "xsl-before-float":
 * - It is an error if the fo:float occurs as a descendant of a flow that is not assigned to one or more
 *   region-body regions, or of an fo:block-container that generates absolutely positioned areas. In either
 *   case, the fo:float shall be formatted as though its "float" property was "none".
 * - A block-area with area-class "xsl-before-float" generated by the fo:float may only be descendant from a
 *   before-float-reference-area that is (a) descendant from a "region-reference-area" generated using the
 *   region-master for the region to which the flow that has the fo:float as a descendant is assigned, and
 *   (b) is descendant from the same page containing the anchor-area, or from a page following that page.
 * - The fo:float may not generate any additional block-areas with area-class "xsl-before-float" unless the
 *   page containing the preceding block-area generated by the fo:float contains no other areas with
 *   area-class "xsl-before-float", has an empty main-reference-area, and does not contain a
 *   footnote-reference-area.
 * - The "clear" property does not apply.
 *
 * The following constraints apply to fo:float formatting objects that generate areas with area-class
 * "xsl-side-float":
 * - Each side-float is placed either as a child of the nearest ancestor reference-area of the anchor-area or
 *   as a child of a later reference-area in the same reference-area chain.
 * - Side-floats that are siblings in the area-tree may overlap their content rectangles.
 * - The description in section 9.5 of [CSS2] shall be used to determine the formatting of the fo:float and
 *   the rendering of normal line-areas and side-floats that are inline-overlapping, with these modifications:
 *    - All references to left and right shall be interpreted as their corresponding writing-mode relative
 *      directions "start" and "end". The "float" property will additionally have the writing-mode relative
 *      values "start" and "end".
 *    - All references to top and bottom shall be interpreted as their corresponding writing-mode relative
 *      directions "before" and "after".
 *    - The phrase "current line box" shall be interpreted to mean the line-area containing the anchor-area
 *      generated by the float. If the anchor-area is a block-area then the "current line box" does not exist.
 *    - Side-floats derive their length in the inline-progression-dimension intrinsically from their child
 *      areas; the length is not determined by an explicit property value.
 *    - A side-float may add to the intrusion adjustment of any inline-overlapping block-area whose nearest
 *      ancestor reference-area is the parent of the side-float. See 4.4.2 Intrusion Adjustments for the
 *      description of intrusion adjustments.
 *    - The user agent may make its own determination, after taking into account the intrusion adjustments
 *      caused by one or more overlapping side-floats, that the remaining space in the
 *      inline-progression-direction is insufficient for the next side-float or normal block-area. The user
 *      agent may address this by causing the next side-float or normal block-area to "clear" one of the
 *      relevant side-floats, as described in the "clear" property description, so the intrusion adjustment
 *      is sufficiently reduced. Of the side-floats that could be cleared to meet this constraint, the
 *      side-float that is actually cleared must be the one whose after-edge is closest to the before-edge of
 *      the parent reference-area.
 *    Note:
 *    The user agent may determine sufficiency of space by using a fixed length, or by some heuristic such as
 *    whether an entire word fits into the available space, or by some combination, in order to handle text and
 *    images.
 *
 * @see https://www.w3.org/TR/xsl11/#CSS2
 * @see https://www.w3.org/TR/xsl11/#intrusadjust
 *
 * Contents:
 * (%block;)+
 *
 * An fo:float is not permitted to have an fo:float, fo:footnote or fo:marker as a descendant.
 * Additionally, an fo:float is not permitted to have as a descendant an fo:block-container that generates an
 * absolutely positioned area.
 * @see https://www.w3.org/TR/xsl11/#fo_float
 */
class FloatElement extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use ValidateFloatElement;

    public function getTagName(): string
    {
        return 'float';
    }

    public function getVisualFallback(Root $root): ?Tag
    {
        return $this->fallback();
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        return $this->fallback();
    }

    /**
     * Common fallback management
     *
     * @return Tag Block tag with every child inside
     */
    private function fallback(): Tag
    {
        // Fallback: place inline.
        $block = new Block();
        $block->children($this->getChildren());

        return $block;
    }
}
