<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\OutOfLine;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Block\Block;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\Footnote as ValidateFootnote;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:footnote is typically used to produce footnote-citations within the region-body of a page and the
 * corresponding footnote in a separate area nearer the after-edge of the page.
 *
 * Areas:
 * The fo:footnote formatting object does not generate any areas. The fo:footnote formatting object returns the
 * areas generated and returned by its child fo:inline formatting object.
 * Additionally the fo:footnote formatting object returns the block-areas with area class "xsl-footnote"
 * generated by its fo:footnote-body child. An area with area-class "xsl-footnote" is placed as a child of a
 * footnote-reference-area.
 *
 * Constraints:
 * The term anchor-area is defined to mean the last area that is generated and returned by the fo:inline child
 * of the fo:footnote.
 * A block-area returned by the fo:footnote is only permitted as a descendant from a footnote-reference-area
 * that is (a) descendant from a "region-reference-area" generated using the region-master for the region to
 * which the flow that has the fo:footnote as a descendant is assigned, and (b) is descendant from the same
 * page that contains the anchor-area, or from a page following the page that contains the anchor-area.
 * The second block-area and any additional block-areas returned by an fo:footnote must be placed on the
 * immediately subsequent pages to the page containing the first block-area returned by the fo:footnote, before
 * any other content is placed. If a subsequent page does not contain a region-body, the user agent must use
 * the region-master of the last page that did contain a region-body to hold the additional block-areas.
 * It is an error if the fo:footnote occurs as a descendant of a flow that is not assigned to one or more
 * region-body regions, or of an fo:block-container that generates absolutely positioned areas. In either
 * case, the block-areas generated by the fo:footnote-body child of the fo:footnote shall be returned to the
 * parent of the fo:footnote and placed in the area tree as though they were normal block-level areas.
 *
 * Contents:
 * (inline,footnote-body)
 *
 * An fo:footnote is not permitted to have an fo:float, fo:footnote, or fo:marker as a descendant.
 * Additionally, an fo:footnote is not permitted to have as a descendant an fo:block-container that generates
 * an absolutely positioned area.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_footnote
 */
class Footnote extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use ValidateFootnote;

    public function getVisualFallback(Root $root): ?Tag
    {
        return $this->fallback();
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        return $this->fallback();
    }

    /**
     * Common fallback management
     *
     * @return Tag Block tag with every child inside
     */
    private function fallback(): Tag
    {
        // Fallback: place inline.
        $block = new Block();
        $block->children($this->getChildren());

        return $block;
    }
}
