<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Indexing;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\IndexPageCitationList as W3IndexPageCitationList;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:index-page-citation-list formatting object is used to group together the sets of cited page items
 * generated by its fo:index-key-reference children. Each fo:index-key-reference child provides formatting
 * properties for the corresponding cited page items. The resulting cited page items are sorted and collated
 * together. The ultimate effect of the fo:index-page-citation-list is to generate a formatted list of page
 * numbers and ranges.
 *
 * Areas:
 * The fo:index-page-citation-list formatting object generates and returns one or more normal inline-areas.
 *
 * Trait Derivation:
 * The traits used for formatting the individual parts of the list of page numbers and ranges is described below.
 *
 * Constraints:
 * Note: Although the constraints are described as performing a series of steps, this is solely for the
 * convenience of exposition and does not imply they must be implemented as separate steps in any conforming
 * implementation. A conforming implementation must only achieve the same effect.
 * Step A: Cited page items from all the child fo:index-key-reference formatting objects are sorted in area
 * tree order. There are then two cases: if merge-pages-across-index-key-references has the value
 * "leave-separate", cited page items referring to the same page generated by different fo:index-key-reference
 * formatting objects will be preserved. If merge-pages-across-index-key-references has the value "merge", only
 * one of the cited page items referring to any given page will be preserved, as specified in
 * 7.24.6 merge-pages-across-index-key-references.
 * Step B: consists of merging sequences of three or more sequential cited page items into a cited page item
 * range. It is performed only if the value of merge-sequential-page-numbers is "merge".
 *
 * @see \Lsa\Xsl\Core\Validation\Types\MergeSequentialPageNumbersType
 *
 * Several conditions influence whether or not any two cited page items from the complete set of cited page
 * items are considered sequential. Two cited page items are sequential if and only if all of the following
 * conditions hold:
 * - The cited page items refer to page-viewport-areas that are consecutive children of the root of the area
 *   tree.
 * - They have the same index-class.
 * - Either the cited page items are generated by the same fo:index-key-reference or the value of
 *   merge-ranges-across-index-key-references is "merge".
 * Step C: consists of formatting the cited page items and cited page item ranges into the list of formatted
 * page numbers and ranges. The result is the same as formatting a sequence of result tree fragments
 * corresponding to individual page numbers, any index page number prefix or suffix, range and list separators.
 *
 * For each cited page item, from fo:index-key-reference R, the result areas are the same as the result of
 * formatting:
 * - If R has an fo:index-page-number-prefix child, an fo:inline containing the result-tree fragment that are
 *   the children of the fo:index-page-number-prefix. The traits of the fo:inline are inherited from R, except
 *   for keep-with-next.within-line which has the value "always".
 * - An fo:inline containing the result-tree fragment, defined in 6.6.10 fo:page-number, using the page
 *   referenced by the cited page item as the reference-page, and the fo:page-sequence that generated the
 *   referenced page as the reference-page-sequence. The traits of the fo:inline are inherited from R. If the
 *   page-number-treatment has the value "link", the fo:inline should be a link back to the source of the
 *   reference as for fo:basic-link.
 * - If R has an fo:index-page-number-suffix child, an fo:inline containing the result-tree fragment that are
 *   the children of the fo:index-page-number-suffix. The traits of the fo:inline are inherited from R, except
 *   for keep-with-previous.within-line which has the value "always".
 * @see \Lsa\Xsl\Core\Tags\Inline\PageNumber
 *
 * For each cited page item range the result areas are the same as the result of formatting:
 * - The first cited page item in the range in the same way as a cited page item; see above.
 * - If the fo:index-page-citation-list has an fo:index-page-citation-range-separator child, an fo:inline
 *   containing the result-tree fragment that are the children of the fo:index-page-citation-range-separator.
 *   The traits of the fo:inline are inherited from the fo:index-page-citation-range-separator, except for
 *   keep-with-previous.within-line and keep-with-next.within-line that have the value "always".
 * - Otherwise an fo:character with traits: character with value U+2013 (en dash),
 *   keep-with-previous.within-line and keep-with-next.within-line that have the value "always". All other
 *   traits are inherited from the fo:index-page-citation-list. Implementations may provide an alternative
 *   default, for example to provide a language- or locale-specific index range separator.
 * - The last cited page item in the range in the same way as a cited page item; see above.
 *
 * After each formatted page item or range, except the last, a separator is inserted. The result areas are the
 * same as the result of formatting:
 *
 * If the fo:index-page-citation-list has an fo:index-page-citation-list-separator child, the result-tree
 * fragment that are the children of the fo:index-page-citation-list-separator. The traits of the fo:inline are
 * inherited from the fo:index-page-citation-list-separator.
 *
 * Otherwise an fo:character with traits: character with value U+002C (comma) and
 * keep-with-previous.within-line with value "always", followed by an fo:character with trait: character with
 * value U+0020 (space). All other traits are inherited from the fo:index-page-citation-list. Implementations
 * may provide an alternative default, for example to provide a language- or locale-specific index list
 * separator.
 *
 * Contents:
 * (index-page-citation-list-separator?,index-page-citation-range-separator?,index-key-reference+)
 * @see https://www.w3.org/TR/xsl11/#fo_index-page-citation-list
 */
class IndexPageCitationList extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use W3IndexPageCitationList;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: ignore.
        return null;
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback: ignore.
        return null;
    }
}
