<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Indexing;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Inline\Inline;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\IndexKeyReference as W3IndexKeyReference;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:index-key-reference formatting object is used to generate a set of cited page items for all the
 * occurrences of the specified index-key.
 *
 * A cited page item is a name for a collection containing the following information:
 * - a reference to a page area
 * - a reference to an fo:index-key-reference
 * - an index class.
 *
 * Areas:
 * The fo:index-key-reference does not generate any areas. The containing fo:index-page-citation-list
 * formatting object uses the cited page items that it contains to produce the generated list of page numbers.
 *
 * Constraints:
 * Each fo:index-key-reference formatting object identifies one or more formatting objects in the formatting
 * object tree with an index-key value that matches the ref-index-key property of the fo:index-key-reference.
 * It is an error if there are no such formatting objects. Implementations should recover from this error by
 * ignoring the fo:index-key-reference.
 * If the matched index-key occurs on an fo:index-range-begin, all of the pages whose descendants include areas
 * generated by formatting objects under the index range influence of that fo:index-range-begin are referenced
 * by the generated cited page items.
 * For each formatting object containing a matching index-key, a cited page item is generated for each page
 * whose descendants include areas returned from that formatting object. The index class of these cited page
 * items is taken from that formatting object. If there are no areas returned from that formatting object then
 * a cited page item is generated referring to the page containing the first area returned from a following
 * formatting object, if any, or the last area returned from a preceding formatting object, if any.
 *
 * Note:
 * For example, if the matched index-key occurs on an fo:block and that block spans pages 3 and 4, then pages
 * 3 and 4 are referenced. If the block is wholly contained on page 3, only page 3 is referenced. Equally, if
 * the matched element is an fo:index-range-begin on page 8 and the matching pair fo:index-range-end is on page
 * 10, then pages 8-10 are referenced. If the beginning of the range and the end of the range both occur on
 * page 8, then only page 8 is referenced.
 * Within each fo:index-key-reference, page ranges are expanded to a sequence of individual cited page items
 * and all but one cited page item that refer to the same page are removed. When two cited page items refer to
 * the same page, the cited page item referring to the fo:index-range-begin or fo:index-range-end occurring
 * first in document order is retained. If none of the referenced formatting objects is an fo:index-range-begin
 * or fo:index-range-end, the cited page item referring to the formatting object that occurs first in the page
 * is retained.
 *
 * Note:
 * Duplicates are removed irrespective of index-class.
 *
 * Contents:
 * (index-page-number-prefix?,index-page-number-suffix?)
 *
 * @see https://www.w3.org/TR/xsl11/#fo_index-key-reference
 */
class IndexKeyReference extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use W3IndexKeyReference;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: display an indication that content cannot be correctly rendered.
        return new Inline('This content cannot be correctly rendered');
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback: display an indication that content cannot be correctly spoken.
        return new Inline('This content cannot be correctly spoken');
    }
}
