<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Inline;

use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\InitialPropertySet as ValidateInitialPropertySet;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:initial-property-set auxiliary formatting object specifies formatting properties for the first line
 * of an fo:block.
 *
 * Note:
 * It is analogous to the CSS first-line pseudo-element.
 *
 * In future versions of this Recommendation a property controlling the number of lines, or the "depth" that
 * these initial properties apply to may be added.
 *
 * Areas:
 * The fo:initial-property-set formatting object does not generate or return any areas. It simply holds a set
 * of traits that are applicable to the first line-area of the area that has a value of "true" for the is-first
 * trait and that was generated by the parent fo:block of the fo:initial-property-set.
 *
 * Trait Derivation:
 * The traits on the fo:initial-property-set are taken into account as traits constraining the first line as if
 * the child inline formatting objects of the fo:block, or parts of them in the case of a line-break, that were
 * used in formatting the first line were enclosed by an fo:inline, as a direct child of the fo:block, with
 * those traits.
 *
 * Constraints:
 * None.
 *
 * Contents:
 * EMPTY
 *
 * @see https://www.w3.org/TR/xsl11/#fo_initial-property-set
 */
class InitialPropertySet extends Tag implements HasVisualFallback
{
    use BasicAuralConformance;
    use ExtendedVisualConformance;
    use ValidateInitialPropertySet;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: ignore any properties specified on this object.
        return new self();
    }
}
