<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Inline;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\Leader as ValidateLeader;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:leader formatting object is often used:
 * - in table-of-contents to generate sequences of "." glyphs that separate titles from page numbers
 * - to create entry fields in fill-in-the-blank forms
 * - to create horizontal rules for use as separators
 *
 * Areas:
 * The fo:leader formatting object generates and returns a single normal inline-area.
 *
 * Trait Derivation:
 * If the value of the leader-pattern is "use-content" the block-progression-dimension of the content-rectangle
 * is determined in the same manner as for inline-areas; otherwise it is determined by the rule-thickness trait.
 *
 * Constraints:
 * If the leader's minimum length is too long to place in the line-area, the leader will begin a new line. If
 * it is too long to be placed in a line by itself, it will overflow the line and potentially overflow the
 * reference-area in accordance with that container's overflow trait.
 * The fo:leader formatting object can have any inline formatting objects and characters as its children,
 * except that fo:leaders may not be nested. Its children are ignored unless the value of the leader-pattern
 * trait is "use-content".
 *
 * Note:
 * If the value of the leader-pattern trait is "use-content" and the fo:leader has no children, the leader shall
 * be filled with blank space.
 *
 * The inline-area generated by the fo:leader has a dimension in the inline-progression-direction which shall be
 * at least the leader-length.minimum and at most the leader-length.maximum.
 * For lines-areas that have been specified to be justified, the justified line-area must honor the
 * leader-alignment trait of any inline-areas generated by fo:leaders.
 * If the value of the leader-pattern trait is "dots" or "use-content", the following constraint applies:
 * The inline-area generated by the fo:leader has as its children the areas returned by children of the
 * fo:leader, or obtained by formatting the pattern specified in the leader-pattern trait, repeated an integral
 * number of times. If the width of even a single repetition is larger than the dimension of the inline-area in
 * the inline-progression-direction, the inline-area shall be filled with blank space. The space-start and
 * space-end of the child areas is set to account for the constraints specified in the leader-pattern-width and
 * leader-alignment traits.
 *
 * Note:
 * If it is desired that the leader should stretch to fill all available space on a line, the maximum length of
 * the leader should be specified to be at least as large as the column width.
 *
 * Note:
 * The alignment of the leader may be script specific and may require indicating what alignment point is
 * required, because it is different from the default alignment for the script. For example, in some usage of
 * Indic scripts the leader is aligned at the alphabetic baseline.
 *
 * Note:
 * An fo:leader can be wrapped in an fo:block, yielding a block-area with a line-area containing the leader, to
 * create a rule for separating or decorating block-areas.
 *
 * Contents:
 * (#PCDATA|%inline;)*
 *
 * The content must not contain an fo:leader, fo:inline-container, fo:block-container, fo:float, fo:footnote,
 * or fo:marker either as a direct child or as a descendant.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_leader
 */
class Leader extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateLeader;
}
