<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Other;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\ChangeBarEnd as W3ChangeBarEnd;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:change-bar-end is used to indicate the end of a "change region" that is started by its matching
 * fo:change-bar-begin. See 6.13.2 fo:change-bar-begin for details.
 *
 * Areas:
 * The fo:change-bar-end formatting object does not in itself generate any areas, but it causes areas to be
 * generated by the ancestor fo:page-sequence object, near the start or end edge of a normal-flow-reference-area
 * or region-reference-area.
 *
 * Constraints:
 * Preceding this fo:change-bar-end in document order, there must be an fo:change-bar-begin with which it
 * forms a matching pair. If there is no such fo:change-bar-begin, it is an error, and the implementation
 * should recover by ignoring this fo:change-bar-end.
 *
 * Contents:
 * EMPTY
 *
 * @see https://www.w3.org/TR/xsl11/#fo_change-bar-end
 */
class ChangeBarEnd extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use W3ChangeBarEnd;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: ignore.
        return null;
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback: ignore.
        return null;
    }
}
