<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Other;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\ChangeBarBegin as W3ChangeBarBegin;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:change-bar-begin is used to indicate the beginning of a "change region" that is ended by the
 * subsequent fo:change-bar-end whose change-bar-class property value matches that of the change-bar-class
 * property on this fo:change-bar-begin and is at the same nesting level (relative to other
 * fo:change-bar-begin/fo:change-bar-end pairs with the same change-bar-class property value) of this
 * fo:change-bar-begin.
 *
 * The change region is decorated with a change bar down either the start or end edge of the column. That is,
 * a change bar is generated along side of the areas generated within the region-body's non-conditional
 * reference area by the formatting objects "under the change bar influence". All formatting objects after
 * (in document order) this fo:change-bar-begin and up to the matching fo:change-bar-end (or end of document)
 * are considered under the change bar influence of this fo:change-bar-begin.
 * The position, thickness, style, and color of the generated change bar is determined by the respective
 * properties (see each property definition).
 *
 * Areas:
 * The fo:change-bar-begin formatting object does not in itself generate any areas, but it causes areas to be
 * generated by the ancestor fo:page-sequence object, near the start or end edge of a
 * normal-flow-reference-area or region-reference-area.
 *
 * Constraints:
 * An fo:change-bar-begin/fo:change-bar-end pair is considered a matching pair if (1) the value of their
 * change-bar-class properties are identical and (2) between (in document order) the fo:change-bar-begin and
 * fo:change-bar-end formatting objects, the only occurrences of fo:change-bar-begin and fo:change-bar-end
 * formatting objects of that class (if any) are matching pairs.
 * Following this fo:change-bar-begin in document order, there must be an fo:change-bar-end with which it forms
 * a matching pair. If there is no such fo:change-bar-end, it is an error, and the implementation should
 * recover by assuming the equivalent of a matching fo:change-bar-end at the end of the document.
 * The generated change bar areas run continuously down the start or end edge of the column within the region
 * body.
 *
 * Contents:
 * EMPTY
 *
 * @see https://www.w3.org/TR/xsl11/#fo_change-bar-begin
 */
class ChangeBarBegin extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use W3ChangeBarBegin;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: ignore.
        return null;
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback: ignore.
        return null;
    }
}
