<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Other;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Inline\Inline;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\RetrieveMarker as ValidateRetrieveMarker;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:retrieve-marker is used in conjunction with fo:marker to produce running headers or footers. Typical
 * examples include:
 * - dictionary headers showing the first and last word defined on the page.
 * - headers showing the page's chapter and section titles.
 *
 * Areas:
 * The fo:retrieve-marker does not directly generate any area. It is (conceptually) replaced by the children of
 * the fo:marker that it retrieves.
 *
 * Trait Derivation:
 * The properties and traits specified on the ancestors of the fo:retrieve-marker are taken into account when
 * formatting the children of the retrieved fo:marker as if the children had the same ancestors as the
 * fo:retrieve-marker.
 *
 * Constraints:
 * An fo:retrieve-marker is only permitted as the descendant of an fo:static-content.
 * The fo:retrieve-marker specifies that the children of a selected fo:marker shall be formatted as though
 * they replaced the fo:retrieve-marker in the formatting tree.
 * The properties of the fo:retrieve-marker impose a hierarchy of preference on the areas of the area tree. Each
 * fo:marker is conceptually attached to each normal area returned by the fo:marker's parent formatting object.
 * Additionally, an fo:marker is conceptually attached to each non-normal area that is directly generated by
 * the fo:marker's parent formatting object. Conversely, areas generated by any descendant of an fo:flow may
 * have zero or more fo:marker's conceptually attached. The fo:marker whose children are retrieved is the one
 * that is (conceptually) attached to the area that is at the top of this hierarchy.
 * Every area in the hierarchy is considered preferential to, or "better" than, any area below it in the
 * hierarchy. When comparing two areas to determine which one is better, the terms "first" and "last" refer to
 * the pre-order traversal order of the area tree.
 * The term "containing page" is used here to mean the page that contains the first area generated or returned
 * by the children of the retrieved fo:marker.
 * An area that has an attached fo:marker whose "marker-class-name" property value is the same as the
 * "retrieve-class-name" property value of the fo:retrieve-marker is defined to be a qualifying area. Only
 * qualifying areas have positions in the hierarchy.
 * A qualifying area within a page is better than any qualifying area within a preceding page, except that
 * areas do not have a position in the hierarchy if they are within pages that follow the containing page. If
 * the "retrieve-boundary" property has a value of "page-sequence", then an area does not have a position in
 * the hierarchy if it is on a page from a page-sequence preceding the page-sequence of the containing page.
 * If the "retrieve-boundary" property has a value of "page", then an area does not have a position in the
 * hierarchy if it is not on the containing page.
 * If the value of the "retrieve-position" property is "first-starting-within-page", then the first qualifying
 * area in the containing page whose "is-first" trait has a value of "true" is better than any other area. If
 * there is no such area, then the first qualifying area in the containing page is better than any other area.
 * If the value of the "retrieve-position" property is "first-including-carryover", then the first qualifying
 * area in the containing page is better than any other area.
 * If the value of the "retrieve-position" property is "last-starting-within-page", then the last qualifying
 * area in the containing page whose "is-first" trait has a value of "true" is better than any other area. If
 * there is no such area, then the last qualifying area in the containing page is better than any other area.
 * If the value of the "retrieve-position" property is "last-ending-within-page", then the last qualifying
 * area in the containing page whose "is-last" trait has a value of "true" is better than any other area. If
 * there is no such area, then the last qualifying area in the containing page is better than any other area.
 * If the hierarchy of areas is empty, no formatting objects are retrieved.
 *
 * Contents:
 * EMPTY
 *
 * @see https://www.w3.org/TR/xsl11/#fo_retrieve-marker
 */
class RetrieveMarker extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use ValidateRetrieveMarker;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: display an indication that content cannot be correctly rendered.
        return new Inline('This content cannot be correctly rendered');
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback: display an indication that content cannot be correctly spoken.
        return new Inline('This content cannot be correctly spoken');
    }
}
