<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Other;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Inline\Inline;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\RetrieveTableMarker as W3RetrieveTableMarker;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:retrieve-table-marker is used in conjunction with fo:marker to produce table-headers and
 * table-footers whose content can change over different pages, different regions or different columns.
 *
 * Typical examples include:
 * - dictionary headers showing the first and last word defined in the part of the table on the current page.
 * - subtotals e.g. that give a subtotal of numbers in rows up to the last row on the current page. For pages
 * with multiple columns and/or multiple regions, the subtotal is to be displayed at the bottom of every table
 * "fragment" in every region or column.
 * - table-continued captions that show if a table is continued after the current page, or was a continuation
 * from a previous page.
 *
 * Areas:
 * The fo:retrieve-table-marker does not directly generate any area. It is (conceptually) replaced by the
 * children of the fo:marker that it retrieves.
 *
 * Trait Derivation:
 * The properties and traits specified on the ancestors of the fo:retrieve-table-marker are taken into account
 * when formatting the children of the retrieved fo:marker as if the children had the same ancestors as the
 * fo:retrieve-table-marker.
 *
 * Constraints:
 * An fo:retrieve-table-marker is only permitted as the descendant of an fo:table-header or fo:table-footer or
 * as a child of fo:table in a position where fo:table-header or fo:table-footer is permitted.
 * The fo:retrieve-table-marker specifies that the children of a selected fo:marker shall be formatted as
 * though they replaced the fo:retrieve-table-marker in the formatting tree.
 * The fo:table that is a parent of both the fo:table-body (that has the fo:markers as its descendants) and the
 * fo:table-header or fo:table-footer that has the fo:retrieve-table-marker as its descendant generates one or
 * more normal block-areas. These are are said to be the retrieve scope area set. The retrieve scope area set
 * is limited by the constraints specified by retrieve-boundary-within-table property. An area in the retrieve
 * scope area set is called a retrieve scope area. There is exactly one retrieve scope area that contains the
 * areas generated or returned by the children on the retrieved fo:marker, and that is called the primary
 * retrieve scope area.
 * The properties of the fo:retrieve-table-marker impose a hierarchy of preference on the descendants of the
 * retrieve scope areas. Each fo:marker is conceptually attached to each normal area returned by the fo:marker's
 * parent formatting object. Additionally, an fo:marker is conceptually attached to each non-normal area that is
 * directly generated by the fo:marker's parent formatting object. Conversely, areas generated by any descendant
 * of an fo:flow may have zero or more fo:marker's conceptually attached. The fo:marker whose children are
 * retrieved is the one that is conceptually attached to the area that is at the top of this hierarchy.
 * Every area in the hierarchy is considered preferential to, or "better" than, any area below it in the
 * hierarchy. When comparing two areas to determine which one is better, the terms "first" and "last" refer to
 * the pre-order traversal order of the area tree.
 * An area that has an attached fo:marker whose "marker-class-name" property value is the same as the
 * "retrieve-class-name" property value of the fo:retrieve-table-marker, is defined to be a qualifying area if
 * it is a descendant of a retrieve scope area. Only qualifying areas have positions in the hierarchy.
 * If the value of the "retrieve-position-within-table" property is "first-starting", then the first qualifying
 * area in the primary retrieve scope area whose "is-first" trait has a value of "true" is better than any other
 * area. If there is no such area, then the first qualifying area in the primary retrieve scope area is better
 * than any other area. If there is no such area, then the last qualifying area that is a descendant of a
 * retrieve scope area is better than any other area.
 * If the value of the "retrieve-position-within-table" property is "first-including-carryover", then the first
 * qualifying area in the primary retrieve scope area is better than any other area. If there is no such area,
 * then the last qualifying area that is a descendant of a retrieve scope area is better than any other area.
 * If the value of the "retrieve-position-within-table" property is "last-starting ", then the last qualifying
 * area that is a descendant of a retrieve scope area whose "is-first" trait has a value of "true" is better
 * than any other area. If there is no such area, then the last qualifying area that is a descendant of a
 * retrieve scope area is better than any other area.
 * If the value of the "retrieve-position-within-table" property is "last-ending ", then the last qualifying
 * area that is a descendant of a retrieve scope area whose "is-last" trait has a value of "true" is better than
 * any other area. If there is no such area, then the last qualifying area that is a descendant of a retrieve
 * scope area is better than any other area.
 * If the hierarchy of areas is empty, no formatting objects are retrieved.
 *
 * Contents:
 * EMPTY
 *
 * @see https://www.w3.org/TR/xsl11/#fo_retrieve-table-marker
 */
class RetrieveTableMarker extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use W3RetrieveTableMarker;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: display an indication that content cannot be correctly rendered.
        return new Inline('This content cannot be correctly rendered');
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback: display an indication that content cannot be correctly spoken.
        return new Inline('This content cannot be correctly spoken');
    }
}
