<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Layout;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\PageSequence as ValidatePageSequence;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:page-sequence formatting object is used to specify how to create a (sub-)sequence of pages within a
 * document; for example, a chapter of a report. The content of these pages comes from flow children of the
 * fo:page-sequence as assigned by the flow-map in effect for that fo:page-sequence. The layout of these pages
 * comes from the fo:page-sequence-master or page-master referenced by the master-reference trait on the
 * fo:page-sequence. The sequence of areas returned by each of the flow-object children of the fo:page-sequence
 * are made descendants of the generated pages as described below.
 *
 * Areas:
 * The fo:page-sequence formatting object generates a sequence of viewport/reference pairs, and returns the
 * page-viewport-areas. For each page-reference-area, and each region specified in the page-master used to
 * generate that page-reference-area, the fo:page-sequence object also generates the viewport/reference pair
 * for the occurrence of that region in that page-reference-area, and may generate a
 * before-float-reference-area, footnote-reference-area, and main-reference-area, and one or more
 * normal-flow-reference-areas. The generation of these further areas is described in the descriptions of the
 * fo:simple-page-master, region-masters and fo:flow-map. It may also generate a title-area.
 *
 * All areas generated by an fo:page-sequence have area-class "xsl-absolute".
 * The page-viewport-areas identify one of the sides as a page binding edge. This recommendation does not
 * specify the mechanism for selecting which side is the page binding edge.
 *
 * Note:
 * If the User Agent can determine that the result is to be bound, then the page binding edge of any given page
 * is the edge on which that page is intended to be bound.
 *
 * Commonly the page binding edge of a page with an odd folio-number is the start-edge of that page and the
 * binding-edge of a page with an even folio-number is the end-edge of that page.
 * The binding can be a simple as stapling or may be as complex as producing a book using an imposition scheme.
 * For each formatting object descendant D under the change bar influence of a given fo:change-bar-begin object
 * F (as defined in 6.13.2 fo:change-bar-begin), the fo:page-sequence generates a "change bar area" for each a
 * rea A returned by D, as a child of the ancestor region-area of A. Each change bar area is of class
 * xsl-absolute, with zero margin and padding, with border-end-color given by the change-bar-color of F, with
 * border-end-style given by the change-bar-style of F, with border-end-width given by the change-bar-width of
 * F, with inline progression-dimension equal to zero and block-progression-dimension equal to the dimension
 * of A parallel to the block-progression-dimension of the region-area.
 * The change bar area is positioned to be adjacent to the nearest ancestor area C of A which is either a
 * normal-flow-reference-area or region-reference-area. The change bar area is aligned with A and lies away
 * from C by a distance given by the change-bar-offset of F, with respect to the start-edge or the end-edge of
 * C as determined by the change-bar-placement trait of F.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_change-bar-begin
 *
 * Trait Derivation:
 * The reference-orientation and writing-mode of the region-viewport-areas are determined by the values of the
 * "reference-orientation" and "writing-mode" properties of the fo:page-sequence.
 *
 * Note:
 * The value may be given as an explicit value or the from-page-master-region function may be used to obtain
 * the value specified on the layout formatting object being used to generate the region viewport/reference
 * area pair.
 *
 * Constraints:
 * Each page-viewport-area/page-reference-area pair is generated using a page-master that satisfies the
 * constraints of the page-sequence-master identified by the master-reference trait of the fo:page-sequence or
 * a page-master that was directly identified by the master-reference trait. The region-viewport-area children
 * of such a page-reference-area must correspond to the regions that are children of that page-master.
 * The areas generated by the fo:page-sequence have as their descendants the areas returned by the flows that
 * are children of the fo:page-sequence.
 *
 * The areas returned to the fo:page-sequence by a flow must satisfy five types of constraints:
 * - Completeness. All areas returned by formatting object descendants of the flow children of the
 *   fo:page-sequence become descendants of areas generated by the fo:page-sequence, with the exception of
 *   glyph-areas subject to deletion or substitution as in Sections 4.7.2 Line-building and
 *   4.7.3 Inline-building.
 * - Flow-map association. The areas returned from a flow child of the fo:page-sequence must be descendants of
 *   region-reference-areas generated using regions to which the flow is assigned by the flow-map in effect.
 *     - Areas returned from an fo:static-content with a flow-name of xsl-before-float-separator become
 *       children of the before-float-reference-area of an area associated to an fo:region-body, following all
 *       sibling areas of area-class xsl-before-float.
 *     - Areas returned from an fo:static-content with a flow-name of xsl-footnote-separator become children of
 *       the footnote-reference-area of an area associated to an fo:region-body, preceding all sibling areas of
 *       area-class xsl-footnote.
 *     - If the flow-map-reference is specified, the flow-map in effect is the one described by the fo:flow-map
 *       child of the fo:layout-master-set having a flow-map-name matching the specified value of
 *       flow-map-reference on the fo:page-sequence. If the flow-map-reference is not specified, the flow-map
 *       in effect is the implicit flow-map shown in 6.4.22 fo:flow-map.
 * - Area-class association. Areas returned by flow children of an fo:page-sequence are distributed as follows:
 *    - All areas of area-class xsl-footnote, and all areas returned from an fo:static-content with a flow-name
 *      of xsl-footnote-separator, must be descendants of a footnote-reference-area;
 *    - all areas of area-class xsl-before-float, and all areas returned from an fo:static-content with a
 *      flow-name of xsl-before-float-separator, must be descendants of a before-float-reference-area;
 *    - all other areas must be descendants of a region-reference-area and further they must be descendants of
 *      a main-reference-area child of that region-reference-area if it has one.
 * - Stacking. The stackable areas of a given class returned by children of each flow are properly stacked
 *   within the appropriate reference-area, as described above.
 * - Flow-assignment ordering. The default ordering constraint of 4.7.1 General Ordering Constraints does not
 *   apply to the fo:page-sequence. The default ordering constraint applies to the flow object children inside
 *   each fo:flow; special ordering constraints apply to the child fo:static-content objects.
 *
 * If the flow-map in effect for a page-sequence has a flow-assignment child with flow-source-list S and
 * flow-target-list T and the child flow-name-specifiers of S have flow-name-reference values F1,...,Fm, and
 * the child region-name-specifiers of T have region-name-reference values R1,...,Rn, then for each area-class
 * C, the areas returned to the page-sequence belonging to that class have the same order in the area tree
 * (relative to the region ordering) as their generating formatting objects (relative to the flow ordering).
 * That is, if A and B are areas of area-class C and either A and B are returned by the same flow with A
 * returned prior to B, or A and B are returned by flows with flow-name values Fi and Fj, respectively, for
 * some i and j such that i<j, then one of the following conditions must hold:
 * - the ancestor page-reference-area of A precedes the ancestor page-reference-area of B, or
 * - A and B share the same ancestor page-reference-area, A is a descendant of a region-reference-area
 *   generated using a region whose region-name value is Rk and B is a descendant of a region-reference-area
 *   generated using a region whose region-name value is Rl for some k and l such that k<l, or
 * - A and B are descendants of the same region-reference-area and A precedes B in the pre-order-tree traversal
 *   of the area tree.
 *
 * If a title-area is generated the following constraints must be satisfied:
 * - Completeness. All areas returned by formatting object descendants of the fo:title child of the
 *   fo:page-sequence become descendants of the title-area generated by the fo:page-sequence, with the
 *   exception of glyph-areas subject to deletion or substitution as in Sections 4.7.2 Line-building and
 *   4.7.3 Inline-building.
 * - Stacking. The areas returned by children of the fo:title are properly stacked within the title-area.
 * @see https://www.w3.org/TR/xsl11/#area-linebuild
 * @see https://www.w3.org/TR/xsl11/#area-inlinebuild
 * @see https://www.w3.org/TR/xsl11/#fo_flow-map
 * @see https://www.w3.org/TR/xsl11/#area-genorder
 *
 * The default ordering constraint of section 4.7.1 General Ordering Constraints does apply to the fo:title.
 *
 * Contents:
 * (title?,folio-prefix?,folio-suffix?,static-content*,flow+)
 * @see https://www.w3.org/TR/xsl11/#fo_page-sequence
 */
class PageSequence extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidatePageSequence;
}
