<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Layout;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\RegionBody as ValidateRegionBody;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * Used in constructing a simple-page-master. This region specifies a viewport/reference pair that is located
 * in the "center" of the fo:simple-page-master. The overflow trait controls how much of the underlying
 * region-reference-area is visible; that is, whether the region-reference-area is clipped by its parent
 * region-viewport-area.
 *
 * Note:
 * Typically, for paged media and when no explicit flow map is specified, the areas returned by the fo:flow
 * formatting object in an fo:page-sequence are made to be descendants of a sequence of region-reference-areas
 * that correspond to the region-body. These region-reference-areas are all area descendants of page-areas for
 * which the page-master included an fo:region-body. If the fo:flow flow is assigned to some other region,
 * then the areas returned by the fo:flow are constrained to be descendants of region-reference-areas generated
 * using the assigned region-master.
 *
 * Note:
 * The body region should be sized and positioned within the fo:simple-page-master so that there is room for
 * the areas returned by the flow that is assigned to the fo:region-body and for any desired side regions,
 * that is, fo:region-before, fo:region-after, fo:region-start and fo:region-end's that are to be placed on the
 * same page. These side regions are positioned within the content-rectangle of the page-reference-area. The
 * margins on the fo:region-body are used to position the region-viewport-area for the fo:region-body and to
 * leave space for the other regions that surround the fo:region-body.
 *
 * @see https://www.w3.org/TR/xsl11/PageAndRegion-bodyMargins.gif
 *
 * The spacing between the last four regions and the fo:region-body is determined by subtracting the relevant
 * extent trait on the side regions from the trait that corresponds to the "margin-x" property on the
 * fo:region-body.
 * The fo:region-body may be also be used to provide multiple columns. When the column-count trait is greater
 * than one, then the region-body will be subdivided into multiple columns.
 *
 * Areas:
 * The fo:region-body formatting object is used to generate one region-viewport-area and one
 * region-reference-area whenever an fo:simple-page-master that has an fo:region-body as a child is used to
 * generate a page. A scrolling mechanism shall be provided, in an implementation-defined manner, if the value
 * of the overflow trait is "scroll".
 * The position and size of the region-viewport-area is specified relative to the content-rectangle of the
 * page-reference-area generated by fo:simple-page-master. The content-rectangle of the region-viewport-area
 * is indented from the content-rectangle of the page-reference-area by the values of the "margin-top",
 * "margin-bottom", "margin-left" and "margin-right" properties. The values of the padding and border-width
 * traits must be "0".
 * The region-reference-area generated using an fo:region-body is the child of the region-viewport-area. The
 * "writing-mode" of the fo:region-body defines the column-progression within the region. The
 * inline-progression-direction is used to determine the stacking direction for columns (and the default flow
 * order of text from column-to-column).
 * In addition to the viewport/reference pair, when the region-body is used to generate areas, at least one
 * and up to three additional reference-areas are generated. These reference-areas are the optional
 * before-float-reference-area, the optional footnote-reference-area, and the main-reference-area. The latter
 * reference-area comprises the space left after space is borrowed for the other two reference-areas. The
 * main-reference-area has no padding, border, or space associated with it.
 *
 * Note:
 * If there is no before-float-reference-area or footnote-reference-area child of the region-reference-area,
 * then the content-rectangle of the main-reference-area is coterminous with the content-rectangle of the
 * region-reference-area.
 *
 * The main-reference-area has as its children a sequence of span-reference-areas. These are reference-area
 * block-areas with zero border and padding, whose inline-progression-dimension is equal to that of the
 * main-reference-area, and which are normally stacked within the main-reference-area.
 * Each span-reference-area has one or more reference-area children, designated as normal-flow-reference-areas.
 * The number and placement of the children of a span-reference-area depends on the column-count trait of the
 * span-reference-area. In turn, the formatter must generate precisely enough of these span-reference-areas,
 * and so set their column-count traits, that block-areas returned from the flows with a span of "all" are
 * children of span-reference-areas with column-count equal to 1, and block-areas returned from the flows with
 * a span of "none" are children of span-reference-areas with column-count equal to the refined value of the
 * column-count property of the associated region-reference-area.
 * For each span-reference-area, the number N of normal-flow-reference-area children is equal to the value of
 * the column-count trait.
 * It is an error to specify a column-count other than 1 if the "overflow" property has the value "scroll". An
 * implementation may recover by behaving as if "1" had been specified.
 *
 * The inline-progression-dimension of each of these normal-flow-reference-areas is determined by subtracting
 * (N-1) times the column-gap trait from the inline-progression-dimension of the main-reference-area and
 * dividing that result by N. Using "body-in-size" for the name of the inline-progression-dimension of the
 * span-reference-area and "column-in-size" for the name of the size of the normal-flow-reference-areas in the
 * inline-progression-direction, the formula is:
 * `column-in-size = (body-in-size - (N - 1)*column-gap)/N`
 *
 * The block-progression-dimension of the normal-flow-reference-areas is the same as that of the parent
 * span-reference-area.
 *
 * Note:
 * As noted above, the block-progression-dimension of the span-reference-area may be less than the size of the
 * region-reference-area if a before-float-reference-area or footnote-reference-area are present, or if there
 * is more than one span-reference-area child of the main-reference-area.
 *
 * The normal-flow-reference-areas are positioned within the span-reference-area as follows: The first column
 * is positioned with the before-edge and start-edge of its content-rectangle coincident with the before-edge
 * and start-edge of the content-rectangle of the span-reference-area. The content-rectangle of the Jth
 * normal-flow-reference-area child of the span-reference-area is positioned with its before-edge coincident
 * with the before-edge of the content-rectangle of the span-reference-area and with is start-edge at
 * ((J-1)*(column-in-size + column-gap)) in the inline-progression-direction. This results in the end-edge of
 * the content-rectangle of the Nth normal-flow-reference-area being coincident with the end-edge of the
 * content-rectangle of the span-reference-area.
 *
 * Note:
 * If the writing-mode is "rl-tb", the above description means that the columns are ordered from right-to-left
 * as would be expected. This follows because the start-edge is on the right in an "rl-tb" writing-mode.
 *
 * All areas generated by using the fo:region-body are of area-class "xsl-absolute".
 *
 * Trait Derivation:
 * The reference-orientation and writing-mode of the region-viewport-area are determined by the formatting
 * object that generates the area (see 6.4.5 fo:page-sequence). The reference-orientation of the
 * region-reference-area is set to "0" and is, therefore, the same as the orientation established by the
 * region-viewport-area. The writing-mode of the region-reference-area is set to the same value as that of the
 * region-viewport-area.
 * The remaining traits on the region-viewport-area and region-reference-area are set according to the normal
 * rules for determining the values of traits.
 * The traits on the span-reference-areas and on the normal-flow-reference-areas are determined in the same
 * manner as described in 5 Property Refinement / Resolution.
 * @see \Lsa\Xsl\Core\Tags\Layout\PageSequence
 * @see https://www.w3.org/TR/xsl11/#refinement
 *
 * Constraints:
 * The constraints applicable to all regions (see 6.4.13 fo:simple-page-master) all apply.
 * The inline-progression-dimension of the region-viewport-area is determined by the
 * inline-progression-dimension of the content-rectangle of the page-reference-area minus the values of the
 * start-indent and end-indent traits of the region-master. The start-edge and end-edge of the
 * content-rectangle of the region-viewport-area are determined by the reference-orientation trait on the
 * page-master.
 * The block-progression-dimension of the region-viewport-area is determined by the block-progression-dimension
 * of the content-rectangle for the page-reference-area minus the values of the space-before and space-after
 * traits of the region-master. The before-edge and after-edge of the content-rectangle of the
 * region-viewport-area are determined by the reference-orientation trait on the page-master.
 * The values of the space-before and start-indent traits are used to position the region-viewport-area
 * relative to the before-edge and start-edge of the content-rectangle of the page-reference-area.
 * The constraints on the size and position of the region-reference-area generated using the fo:region-body are
 * covered in the "Constraints applicable to regions" section of 6.4.13 fo:simple-page-master.
 * @see \Lsa\Xsl\Core\Tags\Layout\SimplePageMaster
 *
 * Contents:
 * EMPTY
 * @see https://www.w3.org/TR/xsl11/#fo_region-body
 */
class RegionBody extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateRegionBody;
}
