<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Layout;

use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\RegionAfter as ValidateRegionAfter;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * Used in constructing a simple-page-master. This region specifies a viewport/reference pair that is located
 * on the "after" side of the page-reference-area. In lr-tb writing-mode, this region corresponds to the footer
 * region. The overflow trait controls how much of the underlying region-reference-area is visible; that is,
 * whether the region-reference-area is clipped by its parent region-viewport-area.
 *
 * Areas:
 * The fo:region-after formatting object is used to generate one region-viewport-area and one
 * region-reference-area.
 * The values of the padding and border-width traits must be "0".
 * The after-edge of the content-rectangle of this region-viewport-area is positioned coincident with the
 * after-edge of the content-rectangle of the page-reference-area generated using the parent
 * fo:simple-page-master. The block-progression-dimension of the region-viewport-area is determined by the
 * extent trait on the fo:region-after formatting object.
 * The inline-progression-dimension of the region-viewport-area is determined by the precedence trait on the
 * fo:region-after. If the value of the precedence trait is true, then the inline-progression-dimension
 * extends up to the start-edge and end-edge of the content-rectangle of the page-reference-area. In this case,
 * the region-after region-viewport-area acts like a float into areas generated by the region-start and
 * region-end. If the value of the precedence trait on the fo:region-after is false, then these adjacent
 * regions float into the area generated by the fo:region-after and the extent of the fo:region-after is
 * (effectively) reduced by the incursions of the adjacent regions.
 * The region-reference-area lies on a canvas underneath the region-viewport-area.
 * The size of the region-reference-area depends on the setting of the overflow trait on the region. If the
 * value of that trait is "auto", "hidden", "error-if-overflow", "paginate", or "visible" then the size of the
 * reference-area is the same as the size of the viewport. If the value of the overflow trait is "scroll", the
 * size of the reference-area is equal to the size of the viewport in the inline-progression-direction in the
 * writing-mode for the region and has no constraint in the block-progression-direction (which implies that it
 * grows to hold the distribution of all the content bound to the region).
 *
 * Trait Derivation:
 * The reference-orientation and writing-mode of the region-viewport-area are determined by the formatting
 * object that generates the area (see 6.4.5 fo:page-sequence). The reference-orientation of the
 * region-reference-area is set to "0" and is, therefore, the same as the orientation established by the
 * region-viewport-area. The writing-mode of the region-reference-area is set to the same value as that of the
 * region-viewport-area.
 * The remaining traits on the region-viewport-area and region-reference-area are set according to the normal
 * rules for determining the values of traits.
 *
 * @see \Lsa\Xsl\Core\Tags\Layout\PageSequence
 *
 * Constraints:
 * The constraints on the size and position of the region-reference-area generated using the fo:region-after
 * are covered in the "Constraints applicable to regions" section of 6.4.13 fo:simple-page-master.
 * @see \Lsa\Xsl\Core\Tags\Layout\SimplePageMaster
 *
 * Contents:
 * EMPTY
 * @see https://www.w3.org/TR/xsl11/#fo_region-after
 */
class RegionAfter extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use ValidateRegionAfter;

    public function getVisualFallback(Root $root): ?Tag
    {
        $this->fallback($root);

        return null;
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        $this->fallback($root);

        return null;
    }

    private function fallback(Root $root): void
    {
        // Fallback: include after content of body region is placed

        /**
         * An XSL-FO document must have a region body
         *
         * @var \Lsa\Xsl\Core\Tags\Layout\RegionBody
         */
        $body = $root->xpath('//region-body')->first();
        $body->children($this->getChildren());
        $this->markAsUnrenderable();
    }
}
