<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Tags;

use Lsa\Xml\Utils\Validation\Definition;
use Lsa\Xml\Utils\Validation\Element;
use Lsa\Xml\Utils\Validation\Sequence;
use Lsa\Xsl\Core\Tags\Indexing\IndexKeyReference;
use Lsa\Xsl\Core\Tags\Indexing\IndexPageCitationListSeparator;
use Lsa\Xsl\Core\Tags\Indexing\IndexPageCitationRangeSeparator;
use Lsa\Xsl\Core\Validation\Properties\MergePagesAcrossIndexKeyReferences;
use Lsa\Xsl\Core\Validation\Properties\MergeRangesAcrossIndexKeyReferences;
use Lsa\Xsl\Core\Validation\Properties\MergeSequentialPageNumbers;
use Lsa\Xsl\Core\Validation\PropertyGroups\InheritedProperties;

trait IndexPageCitationList
{
    /**
     * Returns this tag definition
     * Groups together the sets of cited page items generated by
     * its fo:index-key-reference children. The ultimate effect of
     * the fo:index-page-citation-list is to generate a formatted
     * list of page numbers and ranges.
     *
     * @return Definition This tag definition
     */
    public function asDefinition(): Definition
    {
        return (new Definition())
            ->sequence(new Sequence(
                new Element(IndexPageCitationListSeparator::class, maxOccurs: 1),
                new Element(IndexPageCitationRangeSeparator::class, maxOccurs: 1),
                new Element(IndexKeyReference::class, minOccurs: 1, maxOccurs: 'unbounded')
            ))
            ->allows([
                MergeSequentialPageNumbers::class,
                MergeRangesAcrossIndexKeyReferences::class,
                MergePagesAcrossIndexKeyReferences::class,
            ])
            ->inheritables([
                InheritedProperties::class,
            ]);
    }
}
