<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Block;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\Block as ValidateBlock;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:block formatting object is commonly used for formatting paragraphs, titles, headlines, figure and
 * table captions, etc.
 *
 * Areas:
 * The fo:block formatting object generates one or more normal block-areas. The fo:block returns these areas,
 * any page-level-out-of-line areas, and any reference-level-out-of-line areas returned by the children of the
 * fo:block. The fo:block also generates zero or more line-areas as children of the normal block-areas it
 * returns, in accordance with 4.7.2 Line-building.
 *
 * @see https://www.w3.org/TR/xsl11/#area-linebuild
 *
 * Trait Derivation:
 * The .minimum, .optimum, and .maximum components of the half-leading trait are set to 1/2 the difference of
 * the computed value of the line-height property and the computed value of the sum of the text-altitude and
 * text-depth properties. The .precedence and .conditionality components are copied from the line-height
 * property.
 *
 * Note:
 * The usage of the half-leading is described in 4.5 Line-areas.
 * @see https://www.w3.org/TR/xsl11/#area-line
 *
 * Constraints:
 * No area may have more than one normal child area returned by the same fo:block formatting object.
 * The children of each normal area generated by an fo:block must satisfy the constraints specified in
 * 4.7.2 Line-building.
 * In addition the constraints imposed by the traits derived from the properties applicable to this formatting
 * object must be satisfied. The geometric constraints are rigorously defined in 4 Area Model.
 *
 * Contents:
 * (#PCDATA|%inline;|%block;)*
 *
 * In addition this formatting object may have a sequence of zero or more fo:markers as its initial children,
 * optionally followed by an fo:initial-property-set.
 * @see https://www.w3.org/TR/xsl11/#fo_block
 */
class Block extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateBlock;
}
