<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Block;

use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Inline\Inline;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\BlockContainer as ValidateBlockContainer;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:block-container flow object is used to generate a block-level reference-area, typically containing
 * text blocks with a different writing-mode. In addition, it can also be used with a different
 * reference-orientation to rotate its content.
 *
 * Note:
 * The use of this flow object is not required for changing the inline-progression-direction only; in that case
 * the Unicode BIDI algorithm and the fo:bidi-override are sufficient.
 *
 * Areas:
 * The fo:block-container formatting object generates one or more viewport/reference pairs. All generated
 * viewport-areas are subject to the constraints given by the block-progression-dimension and
 * inline-progression-dimension traits of the fo:block-container. The fo:block-container returns these areas
 * and any page-level-out-of-line areas returned by the children of the fo:block-container.
 *
 * Note:
 * In the case that the block-progression-dimension.maximum is other than "auto", then overflow processing may
 * apply. The "repeat" value of overflow can be used to generate multiple viewport/reference pairs if this is
 * desired rather than clipping or scrolling.
 *
 * If the absolute-position trait is "auto", these areas all have an area-class of "xsl-normal". If the
 * absolution-position trait is "absolute" or "fixed" then there is one viewport/reference pair, and its
 * area-class is "xsl-absolute" or "xsl-fixed", respectively.
 *
 * Trait Derivation:
 * The reference-orientation and writing-mode traits of the viewport-area and reference-area come from the
 * fo:block-container. These determine the orientation of the start-edge, end-edge, before-edge and after-edge
 * of the content-rectangle of the viewport-area, and of the padding-, border-, and content-rectangles of the
 * reference-area. The reference-orientation of the reference-area is set to "0" and is, therefore, the same as
 * the orientation established by the viewport-area. The inline-progression-dimension of the reference-area is
 * the same as that of the viewport-area, and may not be "auto" if the inline-progression-direction is
 * different from that of the parent of the fo:block-container. The block-progression-dimension of the
 * reference-area is not constrained; thus the reference-area may be larger than the viewport-area and this may
 * cause the "overflow" property to operate.
 *
 * Note:
 * As a property value applies to each of the areas generated by this flow object the size can vary from
 * instance to instance if the value is "auto" or a <length-range>.
 *
 * Constraints:
 * The children of each reference-area generated by an fo:block-container formatting object must be normal
 * block-areas returned by the children of the fo:block-container, must be properly stacked, and must be
 * properly ordered.
 * Any reference-level-out-of-line areas returned by the children of the fo:block-container are handled as
 * described in 6.12.2 fo:float.
 *
 * @see\Lsa\Xsl\Core\Tags\OutOfLine\FloatElement
 *
 * @see https://www.w3.org/TR/xsl11/#fo_block-container
 */
class BlockContainer extends Tag implements HasVisualFallback
{
    use BasicAuralConformance;
    use ExtendedVisualConformance;
    use ValidateBlockContainer;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback: display indication that content cannot be correctly rendered
        return new Inline('This content cannot be correctly rendered');
    }
}
