<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;
use Lsa\Xml\Utils\Validation\Validators\UnionValidator;
use Lsa\Xsl\Core\Validation\Types\Xsl\LengthType;
use Lsa\Xsl\Core\Validation\Types\Xsl\PercentageType;

/**
 * Validates AlignmentAdjust property.
 *
 * @link https://www.w3.org/TR/xsl11/#alignment-adjust
 */
class AlignmentAdjustType extends Type implements Validator
{
    /**
     * For a glyph, the alignment-point is the intersection of the start-edge of the a
     * llocation-rectangle of the glyph-area and the block-progression-direction position of the
     * alignment-point from the font as specified in 7.9.1 Fonts and Font Data. For other
     * inline-areas, the alignment-point is at the intersection of the start-edge of the
     * allocation-rectangle and the baseline identified by the "alignment-baseline" property if
     * this baseline exists in the baseline-table for the dominant-baseline for the inline-area. If
     * the baseline-identifier does not exist in the baseline-table for the glyph or other inline-area,
     * then the User Agent may either use heuristics to determine where that missing baseline would be
     * or may use the dominant-baseline as a fallback. For areas generated by an fo:external-graphic,
     * or fo:instream-foreign-object, the alignment point is at the intersection of the start-edge and
     * after-edge of the allocation-rectangle of the area.
     */
    public const AUTO = 'auto';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * dominant-baseline of the area.
     */
    public const BASELINE = 'baseline';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "before-edge" baseline of the area.
     */
    public const BEFORE_EDGE = 'before-edge';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "text-before-edge" baseline of the area.
     */
    public const TEXT_BEFORE_EDGE = 'text-before-edge';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "middle" baseline of the area.
     */
    public const MIDDLE = 'middle';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "central" baseline of the area.
     */
    public const CENTRAL = 'central';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "after-edge" baseline of the area.
     */
    public const AFTER_EDGE = 'after-edge';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "text-after-edge" baseline of the area.
     */
    public const TEXT_AFTER_EDGE = 'text-after-edge';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "ideographic" baseline of the area.
     */
    public const IDEOGRAPHIC = 'ideographic';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "alphabetic" baseline of the area.
     */
    public const ALPHABETIC = 'alphabetic';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "hanging" baseline of the area.
     */
    public const HANGING = 'hanging';

    /**
     * The alignment-point is at the intersection of the start-edge of the allocation-rectangle and the
     * "mathematical" baseline of the area.
     */
    public const MATHEMATICAL = 'mathematical';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return new UnionValidator(
            new EnumValidator([
                self::AUTO,
                self::BASELINE,
                self::BEFORE_EDGE,
                self::TEXT_BEFORE_EDGE,
                self::MIDDLE,
                self::CENTRAL,
                self::AFTER_EDGE,
                self::TEXT_AFTER_EDGE,
                self::IDEOGRAPHIC,
                self::ALPHABETIC,
                self::HANGING,
                self::MATHEMATICAL,
                self::INHERIT,
            ]),
            new PercentageType(),
            new LengthType()
        );
    }
}
