<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * Validates the Clear property.
 */
class ClearType extends Type implements Validator
{
    /**
     * Specifies that each area generated by the formatting object must clear every start-float whose
     * parent reference-area is the nearest ancestor reference-area of the generated area, provided
     * the start-float was generated by an fo:float that is before this formatting object, using
     * pre-order traversal order of the formatting tree. Additionally specifies that each area
     * generated by the formatting object must be placed so that the reference-area chain containing
     * the generated area's nearest ancestor reference-area does not contain a later reference-area
     * that is the parent of a start-float generated by an fo:float that is before this formatting
     * object, using pre-order traversal of the formatting tree.
     */
    public const START = 'start';

    /**
     * Specifies that each area generated by the formatting object must clear every end-float whose
     * parent reference-area is the nearest ancestor reference-area of the generated area, provided
     * the end-float was generated by an fo:float that is before this formatting object, using
     * pre-order traversal order of the formatting tree. Additionally specifies that each area
     * generated by the formatting object must be placed so that the reference-area chain containing
     * the generated area's nearest ancestor reference-area does not contain a later reference-area
     * that is the parent of an end-float generated by an fo:float that is before this formatting
     * object, using pre-order traversal of the formatting tree.
     */
    public const END = 'end';

    /**
     * Interpreted as "clear='start'".
     */
    public const LEFT = 'left';

    /**
     * Interpreted as "clear='end'".
     */
    public const RIGHT = 'right';

    /**
     * Specifies that the block-areas returned by the fo:float shall be with area-class
     * "xsl-side-float" and shall be floated toward an edge determined by the page binding edge.
     * If the page binding edge is on the start-edge, it shall be floated toward the start-edge of the
     * reference area. If the binding is the end-edge, it shall be floated toward the end-edge of the
     * reference area. If neither, it shall be floated toward the start-edge of the reference area.
     */
    public const INSIDE = 'inside';

    /**
     * Specifies that the block-areas returned by the fo:float shall be with area-class
     * "xsl-side-float" and shall be floated toward an edge determined by the page binding edge.
     * If the page binding edge is on the start-edge, it shall be floated toward the end-edge of the
     * reference area. If the binding is the end-edge, it shall be floated toward the start-edge of the
     * reference area. If neither, it shall be floated toward the end-edge of the reference area.
     */
    public const OUTSIDE = 'outside';

    /**
     * Specifies that the block-areas generated by the fo:float shall be normal.
     */
    public const NONE = 'none';

    /**
     * The generated box is moved below all floating boxes of earlier elements in the source document.
     */
    public const BOTH = 'both';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::START,
            self::END,
            self::LEFT,
            self::RIGHT,
            self::INSIDE,
            self::OUTSIDE,
            self::NONE,
            self::BOTH,
            self::INHERIT,
        ]));
    }
}
