<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * Validates Float property.
 */
class FloatType extends Type implements Validator
{
    public const INHERIT = 'inherit';

    /**
     * Specifies that the block-areas generated by the fo:float shall be with area-class
     * "xsl-before-float", and shall be descendants of a before-float-reference-area generated by a
     * conditional sub-region of a region-body.
     */
    public const BEFORE = 'before';

    /**
     * Specifies that the block-areas generated by the fo:float shall be with area-class
     * "xsl-side-float" and shall be floated toward the start-edge of the reference area.
     */
    public const START = 'start';

    /**
     * Specifies that the block-areas returned by the fo:float shall be with area-class
     * "xsl-side-float" and shall be floated toward the end-edge of the reference area.
     */
    public const END = 'end';

    /**
     * Interpreted as "float='start'".
     */
    public const LEFT = 'left';

    /**
     * Interpreted as "float='end'".
     */
    public const RIGHT = 'right';

    /**
     * Specifies that the block-areas returned by the fo:float shall be with area-class
     * "xsl-side-float" and shall be floated toward an edge determined by the page binding
     * edge. If the page binding edge is on the start-edge, it shall be floated toward the
     * start-edge of the reference area. If the binding is the end-edge, it shall be floated
     * toward the end-edge of the reference area. If neither, it shall be floated toward the
     * start-edge of the reference area.
     */
    public const INSIDE = 'inside';

    /**
     * Specifies that the block-areas returned by the fo:float shall be with area-class
     * "xsl-side-float" and shall be floated toward an edge determined by the page binding
     * edge. If the page binding edge is on the start-edge, it shall be floated toward the
     * end-edge of the reference area. If the binding is the end-edge, it shall be floated
     * toward the start-edge of the reference area. If neither, it shall be floated toward
     * the end-edge of the reference area.
     */
    public const OUTSIDE = 'outside';

    /**
     * Specifies that the block-areas generated by the fo:float shall be normal.
     */
    public const NONE = 'none';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::INHERIT,
            self::BEFORE,
            self::START,
            self::END,
            self::LEFT,
            self::RIGHT,
            self::INSIDE,
            self::OUTSIDE,
            self::NONE,
        ]));
    }
}
