<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * Validates FontStyle property.
 *
 * @see https://www.w3.org/TR/xsl11/#font-style
 */
class FontStyleType extends Type implements Validator
{
    /**
     * Specifies a font that is classified as "normal" in the UA's font database.
     */
    public const NORMAL = 'normal';

    /**
     * Specifies a font that is classified as "italic" in the UA's font database, or, if that is not
     * available, one labeled 'oblique'. Fonts with Italic, Cursive, or Kursiv in their names will
     * typically be labeled "italic".
     */
    public const ITALIC = 'italic';

    /**
     * Specifies a font that is classified as "oblique" in the UA's font database. Fonts with Oblique,
     * Slanted, or Incline in their names will typically be labeled "oblique" in the font database. A
     * font that is labeled "oblique" in the UA's font database may actually have been generated by
     * electronically slanting a normal font.
     */
    public const OBLIQUE = 'oblique';

    /**
     * Specifies a font that is classified as "backslant" in the UA's font database.
     */
    public const BACKSLANT = 'backslant';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::NORMAL,
            self::ITALIC,
            self::OBLIQUE,
            self::BACKSLANT,
            self::INHERIT,
        ]));
    }
}
