<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * Validates PageCitationStrategy property.
 *
 * @link https://www.w3.org/TR/xsl11/#page-citation-strategy
 */
class PageCitationStrategyType extends Type implements Validator
{
    /**
     * Includes the pages containing, as a descendant, any area that matches the ref-id
     * trait of the formatting object on which this property appears plus any blank pages
     * generated by the referenced formatting object.
     */
    public const ALL = 'all';

    /**
     * Includes the pages containing, as a descendant, any normal area that matches the
     * ref-id trait of the formatting object on which this property appears, and which is
     * either returned to that formatting object or is a descendant of a normal area returned
     * to that formatting object.
     */
    public const NORMAL = 'normal';

    /**
     * Includes the pages containing, as a descendant, any area that matches the ref-id trait
     * of the formatting object on which this property appears. This set of pages includes
     * pages containing as descendants out-of-line areas such as those generated by fo:footnote
     * and fo:float.
     */
    public const NON_BLANK = 'non-blank';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::ALL,
            self::NORMAL,
            self::NON_BLANK,
            self::INHERIT,
        ]));
    }
}
