<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * Validates RelativeAlign property.
 *
 * @link https://www.w3.org/TR/xsl11/#relative-align
 */
class RelativeAlignType extends Type implements Validator
{
    /**
     * For an fo:table-cell: for each row, the first child area of all the cells that start in the row
     * and that have this value is placed such that the before-edge of the content-rectangle is placed
     * at the same distance from the row grid. In addition, at least, one of these first child areas
     * of the cells has to be placed with the before-edge of its allocation-rectangle coincident with
     * the before-edge of the content-rectangle of the table-cell.
     * For an fo:list-item the before-edge of the first area descendant generated by the
     * fo:list-item-label is placed coincident with the before-edge of the area generated by the
     * fo:list-item. Similarly the before-edge of the first area descendant generated by the
     * fo:list-item-body is placed coincident with the before-edge of the area generated by the
     * fo:list-item.
     */
    public const BEFORE = 'before';

    /**
     * For an fo:table-cell: for each row, the first child area of all the cells that start in the row and
     * that have this value is placed such that the dominant-baseline, as specified on the fo:table-row,
     * of the first line is placed at the same distance from the row grid. In addition, at least, one of
     * these first child areas of the cells has to be placed with the before-edge of its
     * allocation-rectangle coincident with the before-edge of the content-rectangle of the table-cell.
     *
     * Note: That is, for all applicable cells the baseline of all the first lines are all aligned and
     * placed the minimum distance down in the block-progression-direction. It should be noted that the
     * start-edges of the content-rectangles of the cells need not align.
     *
     * For an fo:list-item the distance between the baseline of the first line-area of the first area
     * descendant generated by the fo:list-item-label is the same as the distance between the baseline of
     * the first line-area of the first area descendant generated by the fo:list-item-body. In addition,
     * at least, one of these first area descendants has to be placed such that the before-edge of its
     * allocation-rectangle is coincident with the before-edge of the content-rectangle of the list-item.
     */
    public const BASELINE = 'baseline';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::BEFORE,
            self::BASELINE,
            self::INHERIT,
        ]));
    }
}
