<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;
use Lsa\Xml\Utils\Validation\Validators\UnionValidator;
use Lsa\Xsl\Core\Validation\Types\Xsl\SpaceType;

/**
 * Validates SpaceBefore property.
 * `<space>`:
 * - Specifies the minimum, optimum, and maximum values for the space before any areas generated by this
 *   formatting object and the conditionality and precedence of this space.
 *
 * @link https://www.w3.org/TR/xsl11/#space-before
 */
class SpaceBeforeType extends Type implements Validator
{
    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new UnionValidator(
            new SpaceType(),
            new EnumValidator([
                self::INHERIT,
            ])
        ));
    }
}
