<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * Validates SuppressAtLineBreak property.
 *
 * @link https://www.w3.org/TR/xsl11/#suppress-at-line-break
 */
class SuppressAtLineBreakType extends Type implements Validator
{
    /**
     * The value of this property is determined by the Unicode value of the object's character
     * property. The character at code point U+0020 is treated as if 'suppress' had been specified.
     * All other characters are treated as if 'retain' had been specified.
     * This value does not automatically suppress the presentation of the non-breaking-space
     * (U+00A0), the fixed spaces (U+2000 through U+200A), or the ideographic-space (U+3000).
     */
    public const AUTO = 'auto';

    /**
     * The glyph area generated by the fo:character is eligible to be suppressed at the start or
     * end of a line-area depending on the white-space-treatement property. (q.v.)
     */
    public const SUPPRESS = 'suppress';

    /**
     * The glyph area generated by the fo:character shall be placed in the area tree whether or
     * not it first or last in a line-area.
     */
    public const RETAIN = 'retain';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::AUTO,
            self::SUPPRESS,
            self::RETAIN,
            self::INHERIT,
        ]));
    }
}
