<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;
use Lsa\Xml\Utils\Validation\Validators\UnionValidator;
use Lsa\Xsl\Core\Validation\Types\Xsl\LengthType;
use Lsa\Xsl\Core\Validation\Types\Xsl\PercentageType;

/**
 * CSS2 Reference: "vertical-align" property
 * This property affects the vertical positioning inside a line box of the boxes generated by an
 * inline-level element. The following values only have meaning with respect to a parent
 * inline-level element, or to a parent block-level element, if that element generates anonymous
 * inline boxes; they have no effect if no such parent exists.
 *
 * Note: Values of this property have slightly different meanings in the context of tables. Please
 * consult the section on table height algorithms for details.
 *
 * XSL modifications to the CSS definition:
 * The CSS property shall be treated as a shorthand by XSL and maps as follows:
 *
 * baseline
 * - alignment-baseline="baseline"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * top
 * - alignment-baseline="before-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * text-top
 * - alignment-baseline="text-before-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * middle
 * - alignment-baseline="middle"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * bottom
 * - alignment-baseline="after-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * text-bottom
 * - alignment-baseline="text-after-edge"
 * - alignment-adjust="auto"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * sub
 * - alignment-baseline="baseline"
 * - alignment-adjust="auto"
 * - baseline-shift="sub"
 * - dominant-baseline="auto"
 *
 * super
 * - alignment-baseline="baseline"
 * - alignment-adjust="auto"
 * - baseline-shift="super"
 * - dominant-baseline="auto"
 *
 * `<percentage>`
 * - alignment-baseline="baseline"
 * - alignment-adjust="<percentage>"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * `<length>`
 * - alignment-baseline="baseline"
 * - alignment-adjust="<length>"
 * - baseline-shift="baseline"
 * - dominant-baseline="auto"
 *
 * @see https://www.w3.org/TR/xsl11/#vertical-align
 */
class VerticalAlignType extends Type implements Validator
{
    /**
     * Align the baseline of the box with the baseline of the parent box. If the box doesn't have
     * a baseline, align the bottom of the box with the parent's baseline.
     */
    public const BASELINE = 'baseline';

    /**
     * Align the vertical midpoint of the box with the baseline of the parent box plus half the
     * x-height of the parent.
     */
    public const MIDDLE = 'middle';

    /**
     * Lower the baseline of the box to the proper position for subscripts of the parent's box.
     * (This value has no effect on the font size of the element's text.)
     */
    public const SUB = 'sub';

    /**
     * Raise the baseline of the box to the proper position for superscripts of the parent's box.
     * (This value has no effect on the font size of the element's text.)
     */
    public const SUPER = 'super';

    /**
     * Align the top of the box with the top of the parent element's font.
     */
    public const TEXT_TOP = 'text-top';

    /**
     * Align the bottom of the box with the bottom of the parent element's font.
     */
    public const TEXT_BOTTOM = 'text-bottom';

    /**
     * Align the top of the box with the top of the line box.
     */
    public const TOP = 'top';

    /**
     * Align the bottom of the box with the bottom of the line box.
     */
    public const BOTTOM = 'bottom';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new UnionValidator(
            new PercentageType(),
            new LengthType(),
            new EnumValidator([
                self::BASELINE,
                self::MIDDLE,
                self::SUB,
                self::SUPER,
                self::TEXT_TOP,
                self::TEXT_BOTTOM,
                self::TOP,
                self::BOTTOM,
                self::INHERIT,
            ])
        ));
    }
}
