<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Validation\Types;

use Lsa\Xml\Utils\Contracts\Validator;
use Lsa\Xml\Utils\Validation\Base\Type;
use Lsa\Xml\Utils\Validation\Validators\EnumValidator;

/**
 * The 'visibility' property specifies whether the boxes generated by an element are rendered.
 * Invisible boxes still affect layout (set the 'display' property to 'none' to suppress box
 * generation altogether).
 *
 * This property may be used in conjunction with scripts to create dynamic effects.
 *
 * XSL modifications to the CSS definition:
 * Changed initial value to visible; (it is "inherit" in CSS) and made it an inherited property.
 *
 * @link https://www.w3.org/TR/xsl11/#visibility
 */
class VisibilityType extends Type implements Validator
{
    /**
     * The generated box is visible.
     */
    public const VISIBLE = 'visible';

    /**
     * The generated box is invisible (fully transparent), but still affects layout.
     */
    public const HIDDEN = 'hidden';

    /**
     * Please consult the section on dynamic row and column effects in tables. If used on elements
     * other than rows or columns, "collapse" has the same meaning as "hidden".
     */
    public const COLLAPSE = 'collapse';

    public const INHERIT = 'inherit';

    public function getValidator(): Validator
    {
        return $this->cache(new EnumValidator([
            self::VISIBLE,
            self::HIDDEN,
            self::COLLAPSE,
            self::INHERIT,
        ]));
    }
}
