<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Table;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\TableAndCaption as ValidateTableAndCaption;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:table-and-caption flow object is used for formatting a table together with its caption.
 *
 * Note:
 * An fo:table-and-caption may be placed inline by enclosing it in an fo:inline-container.
 *
 * Note:
 * This formatting object corresponds to the CSS anonymous box that encloses the table caption and the table.
 *
 * Areas:
 * The fo:table-and-caption formatting object generates one or more normal block-areas. The
 * fo:table-and-caption returns these areas, any page-level-out-of-line areas, and any
 * reference-level-out-of-line areas returned by the children of the fo:table-and-caption.
 *
 * Constraints:
 * No area may have more than one normal child area returned by the same fo:table-and-caption formatting object.
 * The children of the areas generated by the fo:table-and-caption are one or two areas; one for the table
 * caption and one for the table itself. These are positioned relative to each other as specified by the
 * caption-side trait. They are placed relative to the content-rectangle of the generated area as specified
 * by the text-align trait.
 *
 * Contents:
 * (table-caption?,table)
 *
 * In addition this formatting object may have a sequence of zero or more fo:markers as its initial children.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_table-and-caption
 */
class TableAndCaption extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateTableAndCaption;
}
