<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Table;

use Lsa\Xml\Utils\Xml\Attribute;
use Lsa\Xsl\Core\Contracts\HasAuralFallback;
use Lsa\Xsl\Core\Contracts\HasVisualFallback;
use Lsa\Xsl\Core\Tags\Layout\Root;
use Lsa\Xsl\Core\Traits\ExtendedAuralConformance;
use Lsa\Xsl\Core\Traits\ExtendedVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\TableCaption as ValidateTableCaption;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:table-caption formatting object is used to contain block-level formatting objects containing the
 * caption for the table only when using the fo:table-and-caption.
 *
 * Areas:
 * The fo:table-caption formatting object generates one or more normal reference-areas. The fo:table-caption
 * returns these reference-areas and any page-level-out-of-line areas returned by the children of the
 * fo:table-caption.
 *
 * Constraints:
 * For the case when the value of the caption-side trait is "before" or "after" the inline-progression-dimension
 * of the content-rectangle of the generated reference-area is equal to the inline-progression-dimension of the
 * content-rectangle of the reference-area that encloses it.
 * When the value is "start" or "end" the inline-progression-dimension of the generated reference-area is
 * constrained by the value of the inline-progression-dimension trait.
 * When the value is "top", "bottom", "left", or "right" the value is mapped in the same way as for
 * corresponding properties (see 5.3 Computing the Values of Corresponding Properties) and the property is then
 * treated as if the corresponding value had been specified.
 * If the caption is to be positioned before the table, the areas generated by the fo:table-caption shall be
 * placed in the area tree as though the fo:table-caption had a "keep-with-next" property with value "always".
 * If the caption is to be positioned after the table, the areas generated by the fo:table-caption shall be
 * placed in the area tree as though the fo:table-caption had a "keep-with-previous" property with value
 * "always".
 * No area may have more than one normal child area returned by the same fo:table-caption formatting object.
 * The children of each normal area returned by an fo:table-caption formatting object must be normal block-areas
 * returned by the children of the fo:table-caption, must be properly stacked, and must be properly ordered.
 * Any reference-level-out-of-line areas returned by the children of the fo:table-caption are handled as
 * described in 6.12.2 fo:float.
 *
 * Contents:
 * (%block;)+
 *
 * In addition this formatting object may have a sequence of zero or more fo:markers as its initial children.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_table-caption
 */
class TableCaption extends Tag implements HasAuralFallback, HasVisualFallback
{
    use ExtendedAuralConformance;
    use ExtendedVisualConformance;
    use ValidateTableCaption;

    public function getVisualFallback(Root $root): ?Tag
    {
        // Fallback:
        // caption-side="start" becomes caption-side="before"
        // caption-side="end" becomes caption-side="after"
        // caption-side="left" becomes caption-side="before"
        // caption-side="right" becomes caption-side="after"
        return $this->fallback();
    }

    public function getAuralFallback(Root $root): ?Tag
    {
        // Fallback:
        // caption-side="start" becomes caption-side="before"
        // caption-side="end" becomes caption-side="after"
        // caption-side="left" becomes caption-side="before"
        // caption-side="right" becomes caption-side="after"
        return $this->fallback();
    }

    /**
     * Common fallback management
     *
     * @return Tag Current tag, with updated attributes if needed
     */
    private function fallback(): Tag
    {
        if ($this->attributes->has('caption-side') === false) {
            return $this;
        }

        $captionSide = $this->attributes->get('caption-side');
        switch ($captionSide) {
            case 'start':
            case 'left':
                $newValue = 'before';
                break;
            case 'end':
            case 'right':
                $newValue = 'after';
                break;
            default:
                return $this;
        }
        $this->attributes->add(new Attribute('caption-side', $newValue));

        return $this;
    }
}
