<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Table;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\TableColumn as ValidateTableColumn;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:table-column auxiliary formatting object specifies characteristics applicable to table cells that
 * have the same column and span. The most important property is the "column-width" property.
 *
 * Areas:
 * The fo:table-column formatting object does not generate or return any areas. It holds a set of traits that
 * provide constraints on the column widths and a specification of some presentation characteristics, such as
 * background which affects the areas generated by the fo:table (see 6.7.3 fo:table). Inheritable properties
 * may also be specified on the fo:table-column. These can be referenced by the from-table-column() function
 * in an expression.
 *
 * Note:
 * More details, in particular the use of an fo:table-column with number-columns-spanned greater than 1, are
 * given in the description of fo:table and of the from-table-column() function.
 *
 * Constraints:
 * None.
 *
 * Contents:
 * EMPTY
 *
 * @see https://www.w3.org/TR/xsl11/#fo_table-column
 */
class TableColumn extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateTableColumn;
}
