<?php

declare(strict_types=1);

namespace Lsa\Xsl\Core\Tags\Table;

use Lsa\Xsl\Core\Traits\BasicAuralConformance;
use Lsa\Xsl\Core\Traits\BasicVisualConformance;
use Lsa\Xsl\Core\Validation\Tags\TableRow as ValidateTableRow;
use Lsa\Xsl\Core\Xml\Tag;

/**
 * The fo:table-row formatting object is used to group table-cells into rows; all table-cells in a table-row
 * start in the same geometric row on the table grid.
 *
 * Areas:
 * The fo:table-row formatting object does not generate any areas. The fo:table-row formatting object returns
 * the sequence of areas created by concatenating the sequences of areas returned by each of the children of
 * the fo:table-row. The fo:table-row holds a specification of some presentation characteristics, such as
 * background which affects the areas generated by the fo:table (see 6.7.3 fo:table).
 *
 * Constraints:
 * The order of concatenation of the sequences of areas returned by the children of the fo:table-row is the
 * same order as the children are ordered under the fo:table-row.
 * The method for determining the height of the row in the grid is governed by the row-height trait.
 *
 * Contents:
 * (table-cell+)
 *
 * In addition this formatting object may have a sequence of zero or more fo:markers as its initial children.
 *
 * @see https://www.w3.org/TR/xsl11/#fo_table-row
 */
class TableRow extends Tag
{
    use BasicAuralConformance;
    use BasicVisualConformance;
    use ValidateTableRow;
}
